### ISSUE TITLE
Add Privoxy

### ISSUE THREAD

**Issue by gurabli** [qdm12/private-internet-access-docker#10]
Nice work!
Maybe you shoulf consider to add Privoxy to the container? Then the Privoxy port can be used as a proxy to route browsers and other apps over the VPN connection. 

Take a look at binhex container: https://github.com/binhex/arch-delugevpn

**Comment by qdm12** [comment]
Hi there!

Thanks for the idea!
I was planning on having a VPN server built-in forwarding to the PIA VPN to do that, how do you think it's better/worst? I'll look into that during next week.

**Comment by qdm12** [comment]
Hi there, just a small ping, I haven't had time to look into adding an openvpn server to the container. I first need to rework the container (doc, run as non-root *ideally* etc.). Also I think that adding a proxy/vpn server on top is not really great in the Docker spirit of 1 process per container (although I am already using Unbound as a background process....). I will try to add a VPN/Proxy server with another container instead and update the readme to show how to do it. You probably can use a VPN server with `net="container:pia"` and some published ports. What do you think?

**Comment by gurabli** [comment]
You are right about one process/container.
Unbound is great to have, I think you can leave it. It is a custom option, so one can decide to use it or not (I use it). 

I still think Privoxy can also be included, as a custom ENV option. But, to have a separate Privoxy container is also a great way, and linked to VPN container. I leave this up to you. Not so familiar with Privoxy to know how to configure properly with custom sevices, options, so I can't be of too much help (except testing). Like great adblock lists can be added to Privoxy.

OpenVPN-AS is a great idea too.

**Comment by qdm12** [comment]
I recently made a [SSH Socks Server container](https://github.com/qdm12/ssh-socks-server-docker), I think it could be used with `network: "container:pia"`. I will test it soon and add it to the readme if it works. If it works without modification, hiproxy etc. should work the same without problem.

**Comment by qdm12** [comment]
Sorry I haven't got much time to work on this. I will close it for now, but it's on the TODO list in the readme and I'll hopefully get working on it some time. Thanks !
