### ISSUE TITLE
Feature request: Shadowsocks client container tailored for this container

### ISSUE THREAD

**Issue by qdm12** [qdm12/private-internet-access-docker#108]
1. What's the feature?

Have a Shadowsocks client container (UDP+TCP proxy) tailored for connecting to this container's Shadowsocks server. Also add documentation/schema to the readme for it.

2. Why do you need this feature?

- Other containers can connect to that shadowsocks client container
- Other containers won't have to be restarted if this vpn container loses its connection
- Automatically reconnects when Shadowsocks server is back online

It should indirectly fix the following issues: #50 #82 #92 

And may fix the issues: #37 , #62 

It would allow the feature request #91 to be developed

**Comment by gurabli** [comment]
Excited to see this in work.
And how should I connect a container? 
And will everything be routed only over VPN, including DNS?

**Comment by qdm12** [comment]
- You can just connect to the container with `--network_mode="container:ssclient"`  for example. The difference is it should never lose its network stack unlike a vpn client container on reconnection.
- It will route only TCP and UDP (so for example no ping ICMP packets), but most traffic uses TCP (http/email/etc.) or UDP (voice/dns) so that should be fine.

**Comment by gurabli** [comment]
I hope you are progressing with the container, as I keep loosing connection every day :)

**Comment by Frepke** [comment]
Any new on this one?

**Comment by qdm12** [comment]
Hello gurabli and Frepke, after consideration, I think that won't solve the problem as updating that new shadowsocks client container would have the same effect as the current problem, so it's really just moving the problem and not solving it.

I think #144 might be a good solution for disconnection problems.

For updating the container, stopping the container will essentially break the connection with connected containers. Maybe there is another Docker networking way to do that.

Otherwise I was thinking of a self updating program in the container to avoid stopping/restarting the container, but that will likely come later once we have a way to live change settings like a web ui and built in http server (see #91 and #147 ).

I'll close the issue but feel free to comment more 😉
