### ISSUE TITLE
Suggestion: use VPN's affiliate programs

### ISSUE THREAD

**Issue by burkasaurusrex** [qdm12/private-internet-access-docker#109]
Hey @qdm12 - I really appreciate all the work you're doing on this.

I might suggest putting affiliate links for signups as a way to support your effort? [PIA](https://www.privateinternetaccess.com/pages/affiliates/) has one, [Mullvad](https://mullvad.net/en/help/policy-reviews-advertising-and-affiliates/) unfortunately does not, and (eventually) [Windscribe](https://windscribe.com/affiliate) has one as well.

It's a small gesture, but I'm happy to cancel my VPN accounts and sign up using your affiliate link. I'm sure others might as well.

**Comment by qdm12** [comment]
Hi @burkasaurusrex that's a great idea, thanks for the research! Never thought myself about doing that. I'll add it in the coming days, once the readme gets reworked 😉  (so after #106 and #108 ). In the meantime, there is also that [Github sponsor program](https://github.com/sponsors/qdm12) if you feel like donating a dollar a month 🥇  No pressure though!

**Comment by qdm12** [comment]
Sent an application to private internet access and an email to Windscribe to set this up. Although for PIA, in their terms and conditions, if you are an existing user and sign up again using the affiliate link, I don't get anything 😄  Except if you change VPN provider....
