### ISSUE TITLE
Check firewall and ipv6

### ISSUE THREAD

**Issue by gurabli** [qdm12/private-internet-access-docker#11]
1) 
How can I make sure that the firewall rules are correct (like the killswitch)?
For example, can I stop/kill the vpn service inside the container (if yes, how, don't know on Alpine). 

2)
How can I check the DNS server being used and to check for DNS leak? 

3)
Do you disable ipv6 completely? 

Many thanks!

**Comment by qdm12** [comment]
1. You can try with `--entrypoint=/bin/sh` and then test which ports are opened, launch openvpn manually etc. Maybe you can remove the entrypoint line from the Dockerfile and build the image if this doesn't work.
1. Same as 1. and probably some Googleing! 
1. I think so, it's disabled on unbound.conf (dns) so there can't be any IPv6 resolved. I may add ipv6 later on but it's a lot of troubles oddly.
