### ISSUE TITLE
Bug: TinyProxy is refusing connections

### ISSUE THREAD

**Issue by bcjacob** [qdm12/private-internet-access-docker#118]
1. What VPN service provider are you using?

    - [x] PIA
    - [ ] Mullvad
    - [ ] Windscribe

2. What's the version of the program?

Latest
   

3. What are you using to run the container?

    - [ ] Docker run
    - [x] Docker Compose
    - [ ] Kubernetes
    - [ ] Docker stack
    - [ ] Docker swarm
    - [ ] Podman
    - [ ] Other:

4. What's wrong? (please share some of your logs, and maybe configuration)

TinyProxy is refusing connections.  I went back to the release tagged as rename-encryption and it worked again: Running version rename-encryption built on 2020-03-26T11:58:15Z (commit 38fb859).  I don't really see anything in the logs to provide an explanation.  

5. Is this urgent?

    - [ ] Yes
    - [x] No

**Comment by bcjacob** [comment]
log with older release looks like this:

`2020-03-30T01:47:14.971Z  INFO    tinyproxy: INFO      Mar 30 01:47:14 [54]: Initializing tinyproxy ...
pia         | 2020-03-30T01:47:14.972Z  INFO    tinyproxy: INFO      Mar 30 01:47:14 [54]: Reloading config file
pia         | 2020-03-30T01:47:14.972Z  INFO    tinyproxy: INFO      Mar 30 01:47:14 [54]: Added basic auth user : bcjacob
pia         | 2020-03-30T01:47:14.973Z  INFO    tinyproxy: INFO      Mar 30 01:47:14 [54]: Disabling transmission of the "Via" header.
pia         | 2020-03-30T01:47:14.973Z  INFO    tinyproxy: INFO      Mar 30 01:47:14 [54]: listen_sock called with addr = '(NULL)'
pia         | 2020-03-30T01:47:14.973Z  INFO    tinyproxy: INFO      Mar 30 01:47:14 [54]: trying to listen on host[0.0.0.0], family[2], socktype[1], proto[6]
pia         | 2020-03-30T01:47:14.974Z  INFO    tinyproxy: INFO      Mar 30 01:47:14 [54]: listening on fd [4]
pia         | 2020-03-30T01:47:14.974Z  INFO    tinyproxy: INFO      Mar 30 01:47:14 [54]: trying to listen on host[::], family[10], socktype[1], proto[6]
pia         | 2020-03-30T01:47:14.974Z  INFO    tinyproxy: INFO      Mar 30 01:47:14 [54]: listening on fd [5]
pia         | 2020-03-30T01:47:14.975Z  INFO    tinyproxy: INFO      Mar 30 01:47:14 [54]: Now running as group "tinyproxy".
pia         | 2020-03-30T01:47:14.975Z  INFO    tinyproxy: INFO      Mar 30 01:47:14 [54]: Now running as user "nonrootuser".
pia         | 2020-03-30T01:47:14.976Z  INFO    tinyproxy: INFO      Mar 30 01:47:14 [54]: Creating child number 1 of 10 ...
pia         | 2020-03-30T01:47:14.976Z  INFO    tinyproxy: INFO      Mar 30 01:47:14 [54]: Creating child number 2 of 10 ...
pia         | 2020-03-30T01:47:14.977Z  INFO    tinyproxy: INFO      Mar 30 01:47:14 [54]: Creating child number 3 of 10 ...
pia         | 2020-03-30T01:47:14.977Z  INFO    tinyproxy: INFO      Mar 30 01:47:14 [54]: Creating child number 4 of 10 ...
pia         | 2020-03-30T01:47:14.978Z  INFO    tinyproxy: INFO      Mar 30 01:47:14 [54]: Creating child number 5 of 10 ...
pia         | 2020-03-30T01:47:14.978Z  INFO    tinyproxy: INFO      Mar 30 01:47:14 [54]: Creating child number 6 of 10 ...
pia         | 2020-03-30T01:47:14.979Z  INFO    tinyproxy: INFO      Mar 30 01:47:14 [54]: Creating child number 7 of 10 ...
pia         | 2020-03-30T01:47:14.980Z  INFO    tinyproxy: INFO      Mar 30 01:47:14 [54]: Creating child number 8 of 10 ...
pia         | 2020-03-30T01:47:14.982Z  INFO    tinyproxy: INFO      Mar 30 01:47:14 [54]: Creating child number 9 of 10 ...
pia         | 2020-03-30T01:47:14.983Z  INFO    tinyproxy: INFO      Mar 30 01:47:14 [54]: Creating child number 10 of 10 ...
pia         | 2020-03-30T01:47:14.983Z  INFO    tinyproxy: INFO      Mar 30 01:47:14 [54]: Finished creating all children.
pia         | 2020-03-30T01:47:14.984Z  INFO    tinyproxy: INFO      Mar 30 01:47:14 [54]: Setting the various signals.
pia         | 2020-03-30T01:47:14.984Z  INFO    tinyproxy: INFO      Mar 30 01:47:14 [54]: Starting main loop. Accepting connections.`

Current release:
`2020-03-30T01:55:43.263Z  INFO    tinyproxy configurator: generating tinyproxy configuration file
pia         | 2020-03-30T01:55:43.263Z  INFO    firewall configurator: accepting any input traffic on port 8888
pia         | 2020-03-30T01:55:43.270Z  INFO    tinyproxy configurator: starting tinyproxy server`

**Comment by qdm12** [comment]
I found the bug (but in bed on my phone :smile:), I just need to remove the line `deluser tinyproxy` from the Dockerfile as it also removes the group `tinyproxy` precised in the generated tinyproxy config file, hence preventing tinyproxy to start. I'll do that tomorrow morning (EST timezone).

Thanks for creating the issue anyway!
