### ISSUE TITLE
Surfshark as provider

### ISSUE THREAD

**Issue by Frepke** [qdm12/private-internet-access-docker#122]
1. What's the feature?
Another vpn provider

2. Why do you need this feature?
They're cheap at the moment
Fast
Good reviewed (mostly)
Situated on the Virgin Islands

3. Extra information?

**Comment by Frepke** [comment]
Here are the Surfshark config-files: [https://api.surfshark.com/v1/server/configurations](url)

**Comment by Frepke** [comment]
Any news on this, no hurry but I would like to test this before my PIA subscription ends 😀

**Comment by qdm12** [comment]
Done 😉  It's merged in latest (cross building [here](https://github.com/qdm12/private-internet-access-docker/runs/720153860?check_suite_focus=true))

**Comment by Frepke** [comment]
Info: the surfshark regions with st00x at the end are servers with static IP's. You should always get the same IP address when connected to the same region.

**Comment by qdm12** [comment]
Ah good to know, I'll add that to the wiki.

Although you can specify `TARGET_IP` which *should* do the same.

**Comment by qdm12** [comment]
Thanks! I've added it to the wiki about Surfshark.
