### ISSUE TITLE
Feature request: IP_STATUS_FILE

### ISSUE THREAD

**Issue by C2BB** [qdm12/private-internet-access-docker#123]
Would it be possible to include an option to write the VPN IP out to a file, similar to PORT_FORWARDING_STATUS_FILE?

**Comment by C2BB** [comment]
I slapped this together and added it to my connected rtorrent container to get me by for now.

    command: /bin/sh -c 'while [ 1 ]; do \
        PIA_PORT=$(cat /config/forwarded_port); \
        PIA_IP=$(ip route list dev eth0 | awk "/^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+ via / {print \$1}"); \
        sed -i "/port_range/c\port_range = $PIA_PORT-$PIA_PORT" /config/rtorrent/rtorrent.rc; \
        sed -i "/dht.port.set/c\dht.port.set = $PIA_PORT" /config/rtorrent/rtorrent.rc; \
        sed -i "/network.local_address.set/c\network.local_address.set = $PIA_IP" /config/rtorrent/rtorrent.rc; done'

**Comment by qdm12** [comment]
Nice, thanks! The `ip route list dev eth0` part is definitely useful, I'll adapt it, probably using [horrible hex codes from /proc/net/route](https://github.com/qdm12/private-internet-access-docker/blob/master/internal/firewall/route.go#L32).

It would be nice also to log the actual IP address to use for port forwarding in the Docker logs.

Thanks 👍 

I'll finish this up in the coming week.

**Comment by C2BB** [comment]
Happy to help! Thank you for considering and taking the time.

**Comment by qdm12** [comment]
It should write the IP address to `/ip` by default, as soon as the VPN tunnel is running. Enjoy 😉  And feel free to re-open the issue if something doesn't work.
