### ISSUE TITLE
Feature request: Remove port forwarding data on container run/stop

### ISSUE THREAD

**Issue by JesterEE** [qdm12/private-internet-access-docker#125]
1. What's the feature?

    - When running the container, if the _PORT_FORWARDING_STATUS_FILE_ variable is specified, clear the data in the associated _PORT_FORWARDING_STATUS_FILE_ volume.
    - When stopping/killing the container, if the _PORT_FORWARDING_STATUS_FILE_ variable is specified, clear the data in the associated _PORT_FORWARDING_STATUS_FILE_ volume.

2. Why do you need this feature?

    The forwarded port data may be stale.  Another app may be reading the _PORT_FORWARDING_STATUS_FILE_ volume to allow communication over the forwarded port, and think communication is possible, when in fact it isn't causing preventable failures. 

    Example 1
    
    1. Run the container specifying a valid port forwarding server **with** the _PORT_FORWARDING_STATUS_FILE_ variable specified.
          - The forwarded port is queried and written to the associated _PORT_FORWARDING_STATUS_FILE_ volume.
    2. Stop the container.
    3. Run the container specifying a valid port forwarding server **with** the _PORT_FORWARDING_STATUS_FILE_ variable specified.
          - The forwarded port is queried, however the query **fails**.
          - The port from the first run will still be in the _PORT_FORWARDING_STATUS_FILE_ volume even though it is not valid for the current connection.

    Example 2
    
    1. Run the container specifying a valid port forwarding server **with** the _PORT_FORWARDING_STATUS_FILE_ variable specified.
          - The forwarded port is queried and written to the associated _PORT_FORWARDING_STATUS_FILE_ volume.
    2. Stop the container.
    3. Run the container specifying any server **without** the _PORT_FORWARDING_STATUS_FILE_ variable specified.
          - The port from the first run will still be in the _PORT_FORWARDING_STATUS_FILE_ volume even though it is not valid for the current connection.

**Comment by qdm12** [comment]
Thanks for the detailed issue!

I think the feature is more to remove the content of the port forwarded file whether `PORT_FORWARDING_STATUS_FILE` is defined or not, at container start time (before querying the port etc.).

I implemented the changes, but just one last question: do you also need the file to be emptied once the container stops/exits or no?

Thanks!

**Comment by JesterEE** [comment]
Practically, for me, no I don't need it emptied on stop/exit.

However, with regard to having accurate data coming from the VPN client, yes, I think it should be cleared whenever there is not a currently forwarded port (i.e. connection start and stop ... and the port forwarding routine should fill it in if applicable for that connection).

**Comment by qdm12** [comment]
In the end, I just added a clear of the port forward status file when the container exits (even when killed, it should clear the file). That way, there is no need to clear it at start as a previous run with port forwarding enabled should had cleared it up. Let me know if you need anything else on that matter 👍
