### ISSUE TITLE
Feature request: Better healthcheck

### ISSUE THREAD

**Issue by qdm12** [qdm12/private-internet-access-docker#133]
1. What's the feature?

- Check IP address found in routes matches public IP address obtained from a 3rd party (i.e. opendns)
- Check IP address matches the region specified, using for example [ipinfo.io](https://ipinfo.io) although there might be a rate limiting.
- (Maybe) check what's your DNS over TLS provider but that might be too convoluted
- Have an API endpoint for the healthcheck for K8s

2. Why do you need this feature?

To know ASAP if the VPN is malfunctioning

3. Extra information?

**Comment by Frepke** [comment]
You can also let users to sign up for free at: [https://ipdata.co](https://ipdata.co)
Limit is 1500 api-calls a day. I use it myself in a shell-script to check the ip-adress from my pia container and also for the connected containers. I mail the results to myself.

```
vpn status: healthy
vpn ip-address: 321.94.134.418
vpn country: Netherlands

✅  sabnzbd
✅  hydra2
✅  qbittorrent

❌  dead   ⚠️  unlinked   ✅  linked

**Comment by qdm12** [comment]
That's cool! How do you check for linked containers? Lookup their names from within the pia container? Combined with #131  that would be sick!

**Comment by Frepke** [comment]
> That's cool! How do you check for linked containers? Lookup their names from within the pia container? Combined with #131  that would be sick!

Unfortunately not,

I know my linked containers, I check and compare their ip-addresses. When they match, their linked. When the connected containers ip-address is different from Pia’s ip-address or simply doesn’t exists, the container is unlinked.

**Comment by qdm12** [comment]
So, after some thoughts...

I'll cycle through a bunch of ip echo websites in order to verify:
- the public ip address matches one of the vpn ip addresses we have in the openvpn configuration file
- the connection is working (so no more github.com)

Now for checking other containers using its network stack are still up, hopefully someone can enlighten us on [that Reddit post](https://www.reddit.com/r/docker/comments/gsrjg3/how_to_detect_containers_using_a_container/). Otherwise, we'll have to skip that feature 😢
