### ISSUE TITLE
Port Forwarding for Deluge

### ISSUE THREAD

**Issue by gurabli** [qdm12/private-internet-access-docker#14]
What do you think about adding Port Forwarding for PIA servers that support this function?
It can be easily added for Deluge and Transmission (I suggest to focus on Deluge). 

Steps would be:
- get open port from PIA server after VPN tunnel is up, write this port to a file (I have scripts for this) 
- check if Deluge port is same or different than the port added to the file
- send deluge_console command to set port to the port obtained and written to the file on first step
- modify iptables to allow port number (I have script for this too) 
- run obtain and check port on each reconnect (port number needs to be obtained within 2 minutes after vpn tunnel is up). 

Needed env_var:
- enable Port Forwarding Yes/No
- set Deluge IP or domain

Should we give it a try?

**Comment by qdm12** [comment]
That sounds like a good idea although security wise that may mean PIA servers could act as man in the middle, I'll check that first. And what would be the point for Deluge for example?

**Comment by gurabli** [comment]
Security wise it is advised to do not use port forwarding at all! Opening the port on VPN is certainly an additional risk compared to closed port. It should be an option to use Port Forwarding or not. And one can decide if better speeds and uploads are more important than better security. 

What do you mean by Deluge?
The point is to automate port setting in Deluge. As PIA changes ports randomly, once a port changed, you will need to change the port in Deluge manually, each time. This can be easily automated and have the port in Deluge always updated to the correct one.

**Comment by qdm12** [comment]
I think it would be great to automate the port change for any application using this container maybe by using some proxy that would keep the same virtual port and update itself to PIA port changes.

Feel free to do a PR or share your scripts! It may take me a few days as I'm quite busy this week.

**Comment by gurabli** [comment]
This is just an idea, I'm also very busy these days. I will share the scripts and will work out something together.
I don't know how other applications can be automated, except Deluge and Transmission. Maybe it can be done with rTorrent and qbittorrent too (will take a look). As for other services, don't think any would need an open port in this range (or you know of any?).

Not sure if it is possible to proxy torrent traffic with a single port over a proxy, I don't know this.

**Comment by gurabli** [comment]
Here you can see a script that few of us put together a year or so ago. It was designed for a split tunnel vpn setup, but the basis is the same. The script will need to be adapted, but it contains all the required information to 1) get the port 2) set iptables 3) set port in Deluge

https://github.com/gurabli/pia-port-forward-docker

In order to this to work, the following conditions needs to be met:

- have access to Deluge Daemon (you will need to allow Deluge Daemon port in container)
- have or set Deluge user/pass to daemon (`auth`), like `user:pass:10`
- set Deluge Daemon ip address (in case of Docker, it will be the host IP, as Deluge container will be linked to VPN container, and the port will be published in VPN container, allowed access by iptables)
- use port forwarding enabled PIA servers if one wants to use port forwarding (The list of servers are [here](https://www.privateinternetaccess.com/archive/forum/discussion/comment/43832/#Comment_43832)
- the port forward request must be made in a time frame of two minutes after connected to the VPN server
- once the port is obtained, it is set in Deluge daemon on-the-fly (see end of the script) with Deluge Console command
- the port is printed to a file if required by other applications
- based on the obtained port, iptables needs to be added to allow incoming connection on the given port
- the new PIA API will change port only when reconnecting. The opened old port needs to be deleted from iptables rules and new port rule added (to prevent unnecessary open ports in firewall and to allow new port)

**Comment by andrewmackrodt** [comment]
+1 for this feature request, it would be awesome if the private-internet-access container could request port forwarding especially after establishing a new connection.Given the current iptables rules INPUT is set to accept so no modification is necessary.

I like the write the port to file approach, I don't particularly want my PIA container to have the docker socket bound to it to be able to notify other containers. A shared volume with a file change listener is good enough.

Currently I'm requesting port forwarding during the [entrypoint](https://github.com/andrewmackrodt/dokarr/blob/develop/share/deluge/init) phase of my deluge container. It works but I suspect port forwarding doesn't carry across to PIA reconnections, e.g. during a timeout.

**Comment by qdm12** [comment]
Noted, I will try to add this feature in the coming weeks.
I am prioritizing a proxy to connect LAN devices to this container, then a CI pipeline build stage for ARM architectures, and then this feature. Thanks for your patience!
