### ISSUE TITLE
Help: ...

### ISSUE THREAD

**Issue by polhaghverdian** [qdm12/private-internet-access-docker#141]
1. What VPN service provider are you using?

    - [X] PIA
    - [ ] Mullvad
    - [ ] Windscribe

2. What's the version of the program?

    `Running version latest build

3. What are you using to run the container?

    - [ ] Docker run
    - [X] Docker Compose
    - [ ] Kubernetes
    - [ ] Docker stack
    - [ ] Docker swarm
    - [ ] Podman
    - [ ] Other:

4. What's the problem?

I get following warnings in the log: 

```
INFO	dns configurator: using DNS address 127.0.0.1 internally
dns configurator: using DNS address 127.0.0.1 system wide
WARN	dns configurator: could not resolve github.com (try 1 of 10): lookup github.com on 127.0.0.11:53: read udp 127.0.0.1:51037->127.0.0.1:53: read: connection refused
```

```
WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1570', remote='link-mtu 1542'
WARNING: 'cipher' is used inconsistently, local='cipher AES-256-CBC', remote='cipher BF-CBC'
WARNING: 'auth' is used inconsistently, local='auth SHA256', remote='auth SHA1'
WARNING: 'keysize' is used inconsistently, local='keysize 256', remote='keysize 128'
```

**Comment by qdm12** [comment]
Hi there, thanks for your issue!

The first warning is fine, it's just the first DNS resolution try to wait for Unbound to be launched. I may add a few milliseconds before the first try to avoid showing the warning.

For the second warnings, that's just PIA doing their strange configuration server side, see [this in the FAQ](https://github.com/qdm12/private-internet-access-docker/blob/master/doc/faq.md#private-internet-access-why-do-i-see-openvpn-warnings-at-start).
