### ISSUE TITLE
Bug: Documentation regression

### ISSUE THREAD

**Issue by sully213** [qdm12/private-internet-access-docker#142]
1. What VPN service provider are you using?

    - [X] PIA
    - [ ] Mullvad
    - [ ] Windscribe

2. What's the version of the program?

    **See the line at the top of your logs**

    `Running version latest built on 2020-04-14T12:22:43Z (commit 422bd8d)`

3. What are you using to run the container?

    - [ ] Docker run
    - [ ] Docker Compose
    - [ ] Kubernetes
    - [ ] Docker stack
    - [ ] Docker swarm
    - [ ] Podman
    - [X] Other: Synology DSM Docker manager

4. What's wrong? (please share some of your logs, and maybe configuration)

ERROR: Cannot open TUN/TAP dev /dev/net/tun: No such device (errno=19)

After restarting my Synology, the previously configured/enabled /dev/net/tun no longer existed. This is likely by design with the Synology DSM software. The problem I'm reporting in regards to this project is that while troubleshooting this problem, I discovered the [documentation for this container previously included the need to have this device already setup](https://github.com/qdm12/private-internet-access-docker/tree/9a2d0ec3ef671a873b2f08e7c8c147fc50a087f0#setup). After following Step 2 of the setup instructions of the linked documentation everything again worked as expected. The current version of documentation does not include this information which affects any Synology users after restart, but also any new users to the container.

An additional step I found helpful (on the Synology) is to [add a boot time script](https://www.synology.com/en-global/knowledgebase/DSM/help/DSM/AdminCenter/system_taskscheduler) to re-establish the /dev/net/tun device after a restart. This may be something helpful to add to your setup documentation as well.

5. Is this urgent?

    - [ ] Yes
    - [x] No

**Comment by qdm12** [comment]
Hi there, thanks for reporting this!

The documentation for that issue is in the [FAQ here](https://github.com/qdm12/private-internet-access-docker/blob/master/doc/faq.md#how-to-fix-openvpn-failing-to-start), so still here although a bit hidden 😉  (I had to because the readme was too big for Docker Hub 😆 ).

Anyway, now the strange thing is that the Go version is meant to create the tun device if it doesn't exist. I tried it on my (arch linux based) server, removing the tun device with `rmmod tun` (from the top of my head), and the container would add the tun device by itself, that's why these instructions are now hidden away in the faq document.

Would you mind trying

1. Stop and remove the pia container
1. Remove the tun device `rmmod tun` I think on Synology
1. Start the pia container, and check if it creates the tun device as expected?

Thanks!

**Comment by sully213** [comment]
Running through this in various iterations this morning, here are my findings.

Starting pia container without pre-defined tun device results in loss of all WAN connectivity from the NAS. I am still able to access the Synology device on the LAN, but the Synology device itself has no access to WAN until after I reboot the entire NAS. Error in the log is the same as reported in the original post. I see no indication in the log that the call to create the device is failing or even happening.

Having the tun device pre-defined (prior to container startup) everything works as expected. If the PIA container is then stopped, WAN connectivity is again lost. Starting the PIA container again then restores WAN connectivity (without having to restart the entire NAS).

**Comment by qdm12** [comment]
My guess is DSM still uses some old Linux with some old Docker and old iptables (firewall), I had similar issues (not the same though) on a Synology machine.

Can you post back results from

```
iptables -v
docker version
```

And then the results of (careful to remove sensitive details of any, there shouldn't be usually)

```
iptables -nvL
```

My guess is the container modifies your firewall (iptables) in a way that should not happen except on old Docker versions. That would explain why you lose WAN access. You're meant to have WAN access blocked only inside the container (to force all traffic to go through the tunnel), and it seems like it affects you entire device instead of the container.

If that's the case, I can add an environment variable to allow disabling the restrictive firewall so that you could use it. Hopefully I can set this up in the coming week.

**Comment by sully213** [comment]
`iptables v1.6.0`

 ```
docker version
Client:
Version:           18.09.8
 API version:       1.39
 Go version:        go1.11
 Git commit:        2c0a67b
 Built:             Fri Sep  6 02:50:44 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11
  Git commit:       1d8275b
  Built:            Fri Sep  6 02:51:05 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```
```
iptables -nvL
Chain INPUT (policy DROP 206K packets, 52M bytes)
 pkts bytes target     prot opt in     out     source               destination
  22M   18G ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
 395K   43M ACCEPT     all  --  lo     *       0.0.0.0/0            0.0.0.0/0
67359 5453K ACCEPT     all  --  *      *       10.0.0.0/23          10.0.0.0/23
    0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:8888
    0     0 ACCEPT     udp  --  *      *       0.0.0.0/0            0.0.0.0/0            udp dpt:8888

Chain FORWARD (policy DROP 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy DROP 29247 packets, 3747K bytes)
 pkts bytes target     prot opt in     out     source               destination
  24M   20G ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
 402K   44M ACCEPT     all  --  *      lo      0.0.0.0/0            0.0.0.0/0
    0     0 ACCEPT     udp  --  *      ovs_bond0  0.0.0.0/0            x.x.x.190       udp dpt:1197
    1    42 ACCEPT     udp  --  *      ovs_bond0  0.0.0.0/0            x.x.x.182       udp dpt:1197
    0     0 ACCEPT     udp  --  *      ovs_bond0  0.0.0.0/0            x.x.x.188       udp dpt:1197
    0     0 ACCEPT     udp  --  *      ovs_bond0  0.0.0.0/0            x.x.x.249       udp dpt:1197
    0     0 ACCEPT     udp  --  *      ovs_bond0  0.0.0.0/0            x.x.x.112       udp dpt:1197
    0     0 ACCEPT     udp  --  *      ovs_bond0  0.0.0.0/0            x.x.x.91        udp dpt:1197
    0     0 ACCEPT     udp  --  *      ovs_bond0  0.0.0.0/0            x.x.x.45        udp dpt:1197
    0     0 ACCEPT     udp  --  *      ovs_bond0  0.0.0.0/0            x.x.x.5         udp dpt:1197
    0     0 ACCEPT     udp  --  *      ovs_bond0  0.0.0.0/0            x.x.x.12        udp dpt:1197
    0     0 ACCEPT     udp  --  *      ovs_bond0  0.0.0.0/0            x.x.x.70        udp dpt:1197
    0     0 ACCEPT     udp  --  *      ovs_bond0  0.0.0.0/0            x.x.x.109       udp dpt:1197
    0     0 ACCEPT     udp  --  *      ovs_bond0  0.0.0.0/0            x.x.x.13        udp dpt:1197
    0     0 ACCEPT     udp  --  *      ovs_bond0  0.0.0.0/0            x.x.x.85        udp dpt:1197
 734K   74M ACCEPT     all  --  *      tun0    0.0.0.0/0            0.0.0.0/0
 130K 7747K ACCEPT     all  --  *      *       10.0.0.0/23          10.0.0.0/23
```

I do have the PIA container running on the host network. Is that correct or do you recommend bridge mode? As for old Linux version, my fully patched and updated DS918+ is running kernel version 4.4.59+ (according to `uname -r`) with bash 4.3.48(1) for the shell if that's of any help to you.

**Comment by qdm12** [comment]
Oh that's why! Yes host network will mess up with your host iptables instead of your container iptables, that's why wan access is shut down 😄  Run it in bridge mode or using a custom Docker network, but host network mode is definitely a no-go.

If you can now try removing the tun device `rmmod tun` and run the container in bridge mode it might work out.

Your iptables and docker version seem fine to me.

**Comment by sully213** [comment]
Re-created the container using bridged network mode and it's a no go. It looks like the container creates the /dev/net/tun device correctly, but it can't access it maybe? This is set to run privileged, I set the OpenVPN environment variable to run as root....

I'm attaching my log output for your review. The smaller one is OpenVPN verbosity set to 0 for a quick look and then another at log level 5. The screenshot here from ash within the container showing that the tun device does exist inside

![Capture](https://user-images.githubusercontent.com/63963317/80754345-de0ce480-8afc-11ea-84ed-66b2ef6d0e31.PNG)

[OVPN Logs.zip](https://github.com/qdm12/private-internet-access-docker/files/4560935/OVPN.Logs.zip)

**Comment by qdm12** [comment]
Thanks so much for the detailed work 👍

So when you install the tun device on your host, the container works right? If so, I'm thinking it really depends on your host OS and/or kernel.

On my side it works on my Arch linux server, Alpine linux server and Windows Docker built-in vm without me having to setup the tun device on the host os.

If the container does work when you setup the tun kernel module on your host, I'll ask some people if they can try it on their machines, to know if it's a common problem (show it in the main readme) or not (keep it in the faq document).

**Comment by sully213** [comment]
Yes, running the PIA container with **host mode** networking AND pre-creating the tun device before container startup works fine (as long as PIA container remains running). Running in bridge mode networking and relying on the container to create the tun device within itself is what is failing for me and is shown in the logs above.

**Comment by qdm12** [comment]
And does it work in bridge mode using `--device=/dev/net/tun` (as on the older documentation)? It always worked in bridge mode for me, even on my Synology NAS.

You should not see the logged warning about the tun device being not available and then created if you give the right device flag and the tun device is setup on your host, when running in bridge mode.

**Comment by sully213** [comment]
That's going to be a bit tougher to try. Synology's Docker implementation tries to be "idiot proof" and therefore also gets in the way of more advanced stuff like attaching external devices. I might be able to do it, but I'm going to have to look into what Synology expects me to do vs. what I can just do outside of the GUI with `docker run` commands via SSH. I had to do something similar with my containrrr/watchtower container to get it to run correctly so as soon as I remember what I did there I'll give this a shot 🤔

**Comment by qdm12** [comment]
Oh yes, you need to ssh in your box to run with that device flag, although you don't need to setup anything extra. I'd recommend you to use docker-compose with a docker-compose.yml though. I'll update the doc and docker-compose file of the repo tonight with the tun device explicitly mapped and refer the commit to this issue.

**Comment by qdm12** [comment]
So I fiddled with my synology nas to test the container, and you're right it turns out you need to `insmod /lib/modules/tun.ko` on your host (everytime it boots as well). Once this is done, no need to pass the device flag, it works.
