### ISSUE TITLE
Feature request: Restart openvpn when it fails and exits

### ISSUE THREAD

**Issue by qdm12** [qdm12/private-internet-access-docker#143]
1. What's the feature?

Restart openvpn from within the container if it disconnects or exits

2. Why do you need this feature?

That **may** allow to keep linked containers connected as the container would not fully restart if openvpn crashes. This should be in a beta testing image tag for a while as it goes against Docker principles of having the Docker daemon manage the restart lifecycle of the container.

3. Extra information?

This should be tested, especially for people when disconnection problems with linked containers such as @frepke (without `OPENVPN_ROOT=on`) or @gurabli

The Docker tag will be `:restart`

**Comment by qdm12** [comment]
Refers to #140

**Comment by Frepke** [comment]
Quentin,

For me the problem isn't a disconnection problem with linked containers due to a problem with the vpn-connection.
The only thing is when I restart the pia container (or recreate when a new version is available), I've to restart the connected containers also. For some reason: network_mode: "service:pia" isn't enough to use the service if the pia container is running again.

**Comment by gurabli** [comment]
I can confirm this too. All the connected containers need rebuilding too.
As reported already, going back to a previous version of qbittorrent solved the connection problem over vpn (reported by others too on qbittorrent github).

**Comment by chrmei** [comment]
Hi Quentin,
many thanks for your work on the issue and the whole project!
Will it then also be possible to force an ovpn restart inside the container - i.e. not just in case of an disconnect or exit?
I'm looking for an option to force restart the ovpn connection through an attached container (network-mode). Unfortunately, I don't have any idea how this could be implemented within the pia-docker.

**Comment by qdm12** [comment]
So my idea now (see #91) would be to have a web ui to restart openvpn, change parameters etc.

As this might take some time undertaking, I think a nice first step would be to have an http server built-in the container with routes triggering actions. For example you could from another connected container

```
wget -qO- http://localhost:8000/openvpn/actions/restart
```

or from a browser do the same assuming you published the port etc.

I will try to do that this weekend.

**Comment by qdm12** [comment]
Hi @chrmei can you please give more details why you need this feature? Please comment back on #147 . I implemented the changes locally, but I would need to know why you need to restart openvpn? Because for now it simply restarts the openvpn process but doesn't change its configuration for example. Thanks!

**Comment by qdm12** [comment]
[Reddit post on restarting the vpn container without restarting the linked containers](https://www.reddit.com/r/docker/comments/gdvod4/restart_container_with_network_stack_shared_with) let's see what the experts say :wink:
