### ISSUE TITLE
Help: Failure conflicting options port publishing and the container type network mode

### ISSUE THREAD

**Issue by nrobfd** [qdm12/private-internet-access-docker#146]
1. What VPN service provider are you using?

    - [X] PIA
    - [ ] Mullvad
    - [ ] Windscribe

2. What's the version of the program?

    Downloaded today

3. What are you using to run the container?

    - [ ] Docker run
    - [ ] Docker Compose
    - [ ] Kubernetes
    - [ ] Docker stack
    - [ ] Docker swarm
    - [ ] Podman
    - [x] Other: Portainer

4. What's the problem?

The container is running and connected to PIA, but when I try to change another Container's network to Container:PIA, I get the following error:

Failure conflicting options port publishing and the container type network mode

5. Is this urgent?

    - [X] Yes
    - [ ] No

**Comment by qdm12** [comment]
You cannot publish ports on the container you want to connect to the pia container in this network mode.

In this network mode, basically your container is on the same 'network host' as the pia container. Therefore publishing ports on the pia container will work for your other container.

Feel free to reopen if you need more help.

**Comment by nrobfd** [comment]
> You cannot publish ports on the container you want to connect to the pia container in this network mode.
> 
> In this network mode, basically your container is on the same 'network host' as the pia container. Therefore publishing ports on the pia container will work for your other container.
> 
> Feel free to reopen if you need more help.

Yeah, I've gathered that. All of the port assignments for the container I'm trying to connect to the PIA container have been removed. Same error persists.

**Comment by qdm12** [comment]
Can you share your run commands or config files?

Are you sure you're not publishing ports on any container other than pia? See [this](https://github.com/dperson/openvpn-client/issues/210) for a similar issue to yours.

**Comment by qdm12** [comment]
I'll close the issue (issue management to see more clearly 😄) but feel free to comment again and I'll reopen it.

**Comment by ArgiesDario** [comment]
> You cannot publish ports on the container you want to connect to the pia container in this network mode.
> 
> In this network mode, basically your container is on the same 'network host' as the pia container. Therefore publishing ports on the pia container will work for your other container.
> 
> Feel free to reopen if you need more help.

I just wanted to add that this is a life saving comment. I spent a lot of time troubleshooting this `Error response from daemon: conflicting options: port publishing and the container type network mode` error, until this made me realise that I just need to open the ports in `gluetun` and not in other containers with `network_mode: "service:gluetun"`
