### ISSUE TITLE
Feature request: HTTP route to restart openvpn

### ISSUE THREAD

**Issue by qdm12** [qdm12/private-internet-access-docker#147]
1. What's the feature?

Have an HTTP server on port `8000` with route GET `/openvpn/actions/restart` to restart manually openvpn.

2. Why do you need this feature?

3. Extra information?

Refers to #143

**Comment by chrmei** [comment]
Hi,
regarding 

2. Why do you need this feature?:

I'm using the container as network container to access multiple sites. Sometimes the specific connection speed gets slow through the PIA network (while it is fast on my host). A restart of the openvpn ( and getting a new IP assigend ) solves that. Am I right that restarting openvpn will be a full re-connect to the pia network for that container? I think a new configuration is not needed for my use case ( but could be a nice feature of course, but I do not need it though ).

Second use case could be to rotate the IP from time to time.

**Comment by qdm12** [comment]
Cool, thanks for clarifying! Yep that's implemented, I'll push it tonight and fix that issue.

Changing the openvpn configuration is the next step :wink: Especially for #91
