### ISSUE TITLE
Automatic update of linked/depends containers

### ISSUE THREAD

**Issue by gurabli** [qdm12/private-internet-access-docker#15]
It is not so much related to PIA container, but more to the use case of it. Most of us will link a container to the PIA container. I know the only easy way to automatically watch and update containers with Watchtower. However, it fails on linked containers and there doesn't seam to be any progress with that (and other) issue. See https://github.com/v2tec/watchtower/issues/188
Maybe you have an idea how to watch/update containers?

**Comment by qdm12** [comment]
That's a good point. However, using `network_mode: "container:pia"` seems to not crash when pia goes down, so you could try that. Also try with `external_links` instead of `links` such as with the nginx proxy described in the readme?

**Comment by gurabli** [comment]
Thanks, I will try container link and see if that works. Btw, do you know what is the main difference between container and service?

**Comment by gurabli** [comment]
Thanks. Tries to change to container inszead of service, but watchtower fails to update with the same error. Does it work for you?

**Comment by qdm12** [comment]
I don't use Watchtower, I prefer to manually do

```bash
docker-compose pull && docker-compose up -d --force-recreate
```

and it works. Does this fail for PIA or your container connected to PIA?

**Comment by qdm12** [comment]
I will close the issue for now as it's more of a Docker issue. There is no alternative for this Docker image I believe unfortunately.
