### ISSUE TITLE
Version for arm (Raspberry & similar)? 

### ISSUE THREAD

**Issue by gurabli** [qdm12/private-internet-access-docker#16]
Hi,
I wonder if you could do a version for arm too, that we could run it on RPi and similar devices. Not sure how difficult is to add support. 
Many thanks!

**Comment by qdm12** [comment]
Yes I will do it today.

**Comment by gurabli** [comment]
Wow, you are extra cool! So much thanks!
This means the docker image will run on any armf based device, like the Rpi, Friendlyelec, Odroid, etc? So cool! 

I wonder what will be the performance on these little devices. Will check it out and see. At the moment I only have Rpi's st home which are very limited by the NIC, but will get a Gigabit speed board and check there.

**Comment by qdm12** [comment]
Try with `docker pull qmcgaw\private-internet-access:arm32v6` although I have not tested it. Let me know how it goes ! Otherwise there is also `qmcgaw\private-internet-access:arm64v8` for other devices in ARM 64 bit.

**Comment by gurabli** [comment]
Great work! I will try it hopefully tonight. Will report back.

**Comment by qdm12** [comment]
Just commenting even if you already know, you can pull the image for ARM using `docker pull qmcgaw\private-internet-access`. There is also the tag `v1` if you feel like staying on a tag 👍
