### ISSUE TITLE
REGION set correctly but results error

### ISSUE THREAD

**Issue by oester** [qdm12/private-internet-access-docker#163]
Updated to the latest build, but when I set my REGION to "CA Toronto", it results in this error:

ERROR	environment variable "REGION" value is "\"ca toronto\"" and can only be one of: AU Melbourne, AU Perth, AU Sydney, Austria, Belgium, CA Montreal, CA Toronto, CA Vancouver, Czech Republic, DE Berlin, DE Frankfurt, Denmark, Finland, France, Hong Kong, Hungary, India, Ireland, Israel, Italy, Japan, Luxembourg, Mexico, Netherlands, New Zealand, Norway, Poland, Romania, Singapore, Spain, Sweden, Switzerland, UAE, UK London, UK Manchester, UK Southampton, US Atlanta, US California, US Chicago, US Denver, US East, US Florida, US Houston, US Las Vegas, US New York City, US Seattle, US Silicon Valley, US Texas, US Washington DC, US West,

**Comment by qdm12** [comment]
Use `CA Toronto`. I'll make it case insensitive, good catch :wink:

**Comment by oester** [comment]
Thanks, that worked.
