### ISSUE TITLE
Trouble accessing docker webUI's via a NAT

### ISSUE THREAD

**Issue by puredrivel** [qdm12/private-internet-access-docker#17]
I'm running docker on a QNAP.  My network is setup as follows:
  PIA[virt adapter @10.0.3.2]  ----->  
                                                            [virt switch @10.0.3.1] --> NAT --> [virt switch @192.168.1.x]
  Deluge[virt adapter @10.0.3.2] --> 

Using a similar docker-compose yml  for the documented deluge example, port 8112 is opened in the pia service.  If I spin up a new docker container on the same virtual switch as PIA (10.0.3.x), I can access the deluge webUI fine, but if I try to access it via 192.168.1.x, it tries to connect and eventually times out.  Am I missing a firewall rule to allow traffic from the NAT?  EXTRA_SUBNETS=192.168.1.0/24 doesn't solve the issue.

**Comment by qdm12** [comment]
The [deluge example given](https://github.com/qdm12/private-internet-access-docker#access-ports-of-pia-connected-containers) involves a nginx container to act as reverse proxy. Did you try with this method? I personally don't use the `EXTRA_SUBNETS` and I only use nginx to access to ports of containers connected to the PIA container. The only disadvantage is that you can't automatically update a container as it will break the Docker links unfortunately.

**Comment by puredrivel** [comment]
I messed around a bit but couldn't figure out why it's not working.  I decided I'm too lazy to start logging network traffic to figure this out so I took your advice, used a reverse proxy and all is well.  Thanks for creating the image and for including some good examples!

**Comment by qdm12** [comment]
You're welcome. If you find a way I would be interested as well! I also went the lazy way as it's a mind maze to figure out the best way to access ports of containers connected to this container. Thanks !
