### ISSUE TITLE
Help: ... Healthcheck error causes permanent unhealthy container state

### ISSUE THREAD

**Issue by djaydev** [qdm12/private-internet-access-docker#170]
**TLDR**: *Describe your issue in a one liner here*

1. Is this urgent?

    - [ ] Yes
    - [x] No

2. What VPN service provider are you using?

    - [ ] PIA
    - [ ] Mullvad
    - [x] Windscribe
    - [ ] Surfshark

3. What's the version of the program?
Running version latest built on 2020-06-04T01:53:16Z (commit 900fa26)

4. What are you using to run the container?

    - [x] Docker run
    - [ ] Docker Compose
    - [ ] Kubernetes
    - [ ] Docker stack
    - [ ] Docker swarm
    - [ ] Podman
    - [ ] Other:

5. Extra information
Using Windscribe VPN, the healthcheck reports different IPs for public and private and causes a permanent healthcheck failure.  Seems to be a recent docker image build, didn't happen a few days ago.  

Logs:

Status | unhealthy
Status |  unhealthy
Failure count | 18
Last output | Public IP address 38.132.118.2yx does not match VPN ip address 38.132.118.2yz on file

Host OS:
Debian

**Comment by qdm12** [comment]
Hello and thanks for reporting this 🥇 

This is related to this [PR discussion](https://github.com/qdm12/private-internet-access-docker/pull/169).

Let's see how it goes now. The healthcheck now compares your public ip address with all the ip addresses in the openvpn configuration file (`/etc/openvpn/config.ovpn`), not just on the one obtained at start. Depending on that, I will adapt the code to update the ip address correctly in the `/ip` file and in the logs, if it ever changes.

**Comment by Frepke** [comment]
> 
> 
> Hello and thanks for reporting this 🥇
> 
> This is related to this [PR discussion](https://github.com/qdm12/private-internet-access-docker/pull/169).
> 
> Let's see how it goes now. The healthcheck now compares your public ip address with all the ip addresses in the openvpn configuration file (`/etc/openvpn/config.ovpn`), not just on the one obtained at start. Depending on that, I will adapt the code to update the ip address correctly in the `/ip` file and in the logs, if it ever changes.

/etc/openvpn/config.ovpn = /etc/openvpn/target.ovpn ?

**Comment by qdm12** [comment]
Oops thanks Frepke

**Comment by djaydev** [comment]
not urgent, container seems to still work well.  

Running version latest built on 2020-06-04T22:14:44Z (commit f6a2aac)

 Public IP address 23.226.141.2xy does not match any of the VPN ip addresses 
 23.82.136.93 443, 
 23.83.91.170 443, 
 23.105.170.139 443, 
 23.226.141.195 443, 
 38.132.118.227 443, 
 67.21.32.145 443, 
 68.235.35.12 443, 
 68.235.50.227 443, 
 86.106.87.83 443, 
 104.168.34.147 443, 
 104.223.127.195 443, 
 107.150.29.131 443, 
 142.234.200.176 443, 
 156.96.59.102 443, 
 162.222.195.67 443, 
 167.160.167.195 443, 
 167.160.172.3 443, 
 173.44.36.67 443, 
 173.208.45.33 443, 
 185.232.22.195 443, 
 198.12.64.35 443, 
 198.147.22.225 443, 
 206.217.128.3 443, 
 206.217.129.227 443, 
 217.138.255.179 443

**Comment by qdm12** [comment]
Hello djaydev and @Frepke 

First of all, I forgot to remove the port number `443`, sorry about that.

But it seems your actual public IP address `23.226.141.2xy` is different than any of the VPN server IP addresses in the openvpn configuration file. My explanation would be that the publicly exposed VPN servers act as gateways to more vpn servers. In this case, it's hard if not impossible to predict the ip address you should have reliably.

On the other hand, on my part, running the container (pia, romania) and then:

1. `docker exec gluetun cat /ip` gives `94.176.148.34`
1. `docker exec gluetun ip route` gives  `(other lines...)94.176.148.34 via 10.0.0.1 dev eth0(other lines)`
1. `docker exec gluetun wget -qO- https://ipinfo.io/ip` gives `94.176.148.34`

Can you please try the 3 commands above after starting a container to see if it gives you the same public IP address? I'm trying to figure out if your public address is different from the start of changes after some time.

**Comment by qdm12** [comment]
I would also need to change the writing/updating of the ip status file `/ip` and the `TARGET_IP` logic if it turns out they are wrong/ineffective 🤔 depending on your answers.

**Comment by djaydev** [comment]
#  cat /ip
67.21.32.145/ 

# ip route
(other lines...)
67.21.32.145 via 172.17.0.1 dev eth0 
(other lines...)

# wget -qO- https://ipinfo.io/ip 
67.21.32.154

**Comment by Frepke** [comment]
>     1. `docker exec gluetun cat /ip` gives `89.46.223.104`
> 
>     2. `docker exec gluetun ip route` gives  `(other lines...)89.46.223.104 via 172.17.0.1 dev eth0(other lines)`
> 
>     3. `docker exec gluetun wget -qO- https://ipinfo.io/ip` gives `89.46.223.105`

**Comment by qdm12** [comment]
Ok thanks guys! So these are vpn gateways, but at least it changes at start.

For now I get your vpn ip address using the ip routes (so no need to call any ip echo website) but that seems to be just the vpn gateway ip, not your actual public ip address.

I'll change the code such that it gets your public IP address from an ip echo service website at start, writes it to `/ip` (and logs it) instead of using the ip routes, and the healthcheck should then work as it is.

I'll message back here once this is done so you can test it out (probably for a few days, to check if you ip ever changes?).

Thanks again!

**Comment by qdm12** [comment]
Hello again, so I added changes to do what I described, let me know if it's still unhealthy for you.

In the logs it should now show at start

```
Gateway VPN IP address: 86.105.25.xx
Public IP address is 86.105.25.xx
```

For me it's the same, I would be curious if it's different for you. Thanks!

**Comment by Frepke** [comment]
> Hello again, so I added changes to do what I described, let me know if it's still unhealthy for you.
> 
> In the logs it should now show at start
> 
> ```
> Gateway VPN IP address: 86.105.25.xx
> Public IP address is 86.105.25.xx
> ```
> 
> For me it's the same, I would be curious if it's different for you. Thanks!

Gateway VPN IP address: 89.46.223.104
Public IP address is 89.46.223.105

The container is healthy as always 😄, but now it runs visible in a healthy state (docker inspect --format "{{json .State.Health }}" gluetun | jq).

**Comment by qdm12** [comment]
Great :+1: Let's see if it stays healthy, I'm curious if the IP address ever changes behind the scenes (=without openvpn restarting).

**Comment by qdm12** [comment]
Mine changes ip address even without openvpn reconnecting. I will remove the ip address check, probably just fallback to resolving github.com in order to verify the connection is still up.
