### ISSUE TITLE
Feature request: Synology insmod needed after reboot

### ISSUE THREAD

**Issue by mawmawmawm** [qdm12/private-internet-access-docker#172]
Hey there,
just an observation I made that might be helpful for other people:
I have this package installed on my Synology via the official GUI Docker client / docker-compose and it works great.
Like mentioned, I had to execute `insmod /lib/modules/tun.ko` as root in order to get the container going.
This however, does not survive a reboot, so after rebooting the NAS this needs to be run again. I only realized this when I looked at the logs for why the container's proxy wasn't working.

Might be worth mentioning in the readme. 

There is a way (through the DSM UI) to execute a task on boot-up (that should do it) but I haven't tried it out yet.

**Comment by qdm12** [comment]
Yes, I had the same issue on a Synology device back then, it resets the network stack somehow on reboots. I'll add a note in the readme about it. Thanks!
