### ISSUE TITLE
Connection to PIA disables ports

### ISSUE THREAD

**Issue by Zed222** [qdm12/private-internet-access-docker#18]
When I use the example docker-compose.yml with my PIA credentials, I am unable to access the web interface for deluge. As published I can access the deluge web interface, but obviously I am not connected to PIA

**Comment by qdm12** [comment]
Sorry this docker compose file is not right, you should use the nginx reverse proxy to access ports of containers connected to PIA, as described above the docker compose section. You could adapt a compose file for your needs. In my case, I have a compose file for pia only and another compose file for deluge with a nginx proxy to access the deluge web ui.

**Comment by Zed222** [comment]
Thanks. Exactly what I have done. Thanks and nice work on the PIA docker.
