### ISSUE TITLE
Feature request: configurable public IP test (url(s) and timeout)

### ISSUE THREAD

**Issue by WoLpH** [qdm12/private-internet-access-docker#186]
1. What's the feature?

Currently the `publicip.go` code is rather static: https://github.com/qdm12/private-internet-access-docker/blob/master/internal/publicip/publicip.go

It would be nice to have a configurable url (something self-hosted that is known to be good) with a configurable timeout for long-distance VPN connections.

2. Why do you need this feature?

I regularly see these messages while starting:
```
2020-07-08T17:34:58.506Z	ERROR	Get "http://ip1.dynupdate.no-ip.com:8245": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

3. Extra information?

Perhaps a space separated list of test addresses through an environment variable with a configurable timeout in milliseconds (to allow for sub-second timeouts if needed)

**Comment by qdm12** [comment]
Good point, I realised that yesterday evening as well. Although I'll just increase the timeout to i. e. 10 seconds for now.

The point was to circle around the urls so we don't get blocked because of too many requests on a single url. Especially since we share an ip with other users, it's might be hard to get the vpn ip address without being blocked.

On a side note, I want to use that ip getting thing periodically as your vpn ip actually changes over time (every n hours), so I would need to update the ip status file and log it out when it changes.

However feel free to let me know if you have another url to use in mind that I can add to the list.

**Comment by qdm12** [comment]
I pushed some changes such that the timeout is now 15 seconds (default timeout for other http operations) instead of 3 seconds, and if it fails, it will retry after 5 seconds of sleep time. It should thus be more resilient and should be working all the time with such big timeout.

**Comment by WoLpH** [comment]
I'm a big fan of ifconfig.me
Or from a regular browser I often use ping.eu

At the very least the https://ifconfig.me/ip should do the trick

**Comment by WoLpH** [comment]
Thanks for the quick fix btw!

**Comment by qdm12** [comment]
I've added (not pushed yet) ifconfig.me. Unfortunately I want to avoid ping.eu as I was before using a regex to find the ip address on a page and would end up with Google's server ip address sometimes haha so not really reliable...

I'm adding changes so the ip address gets queried every hour.

Feel free to ask for more things, I have my hands in the repo and will be working on it the next 1-3 days (mornings/evenings) 😉

**Comment by WoLpH** [comment]
Well... for what it's worth. When `DOT` is enabled I can't resolve anything from a kubernetes pod. Haven't diagnosed the cause of it, I've simply disabled it for now as I don't have any need for DOT anyhow.

**Comment by qdm12** [comment]
Interesting, could you create an issue for that? Copy pasting that one line above is enough 😉 I guess it's because it sets the system wide dns to `127.0.0.1` (unbound). That probably conflicts with K8s somehow, I'll dig into it.

**Comment by WoLpH** [comment]
Actually... I just tested again and it's working now... perhaps it was a temporary glitch or so but it appears to work now. I'll let you know if I have more issues.

**Comment by qdm12** [comment]
Cool, again it might be the little infra randomness k8s puts in 😄  For sure, let me know if anything happens. I should also switch to use K8s at home in the coming days (i've been procrastinating with docker-compose at home really), so that might help debug all that.
