### ISSUE TITLE
Feature request: PureVPN Support

### ISSUE THREAD

**Issue by TGNThump** [qdm12/private-internet-access-docker#192]
PureVPN Support would be awesome.

OpenVPN files can be found here: https://support.purevpn.com/openvpn-files
A list of regions and the appropriate servers can be found here: https://support.purevpn.com/vpn-servers

**Comment by qdm12** [comment]
I just finished nordvpn yesterday and vyprvpn today! Taking a small openvpn break now, I'll do purevpn in the coming week/weekend. Thanks for your patience

**Comment by qdm12** [comment]
Hello!

I finished up the changes for purevpn, can you please try it? I get some openvpn `AUTH_FAILED` error (with my garbage credentials) so I think it should be ready for you to use.

- Docker image: `qmcgaw/private-internet-access:purevpn`
- [Documentation](https://github.com/qdm12/private-internet-access-docker/tree/purevpn#gluetun-vpn-client)
- Example command:

    ```sh
    docker run -it --rm --cap-add=NET_ADMIN -e VPNSP=purevpn -e CITY=Hanoi -e USER=xxx -e PASSWORD=xxx qmcgaw/private-internet-access:purevpn
    ```

If it works, I'll merge it in the master branch / `:latest` docker tag.

Feel free to ask any question.

Thanks!

**Comment by TGNThump** [comment]
Hey, thanks for working on this. I'm getting a certifiate verification error as follows;

```
OpenVPN 2.4.9 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr 20 2020
library versions: OpenSSL 1.1.1g  21 Apr 2020, LZO 2.10
TCP/UDP: Preserving recently used remote address: [AF_INET]188.72.101.130:53
UDP link local: (not bound)
UDP link remote: [AF_INET]188.72.101.130:53
VERIFY ERROR: depth=1, error=self signed certificate in certificate chain: C=HK, ST=HK, L=HongKong, O=PureVPN, OU=IT, CN=PureVPN, name=PureVPN, emailAddress=mail@host.domain
OpenSSL: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
TLS_ERROR: BIO read tls_read_plaintext error
TLS Error: TLS object -> incoming plaintext read error
TLS Error: TLS handshake failed
```

**Comment by qdm12** [comment]
Hi, I noticed I got that for a particular city (Sucre) but not other ones. What location are you trying to use? I'll recheck their tls certificates as I assumed they all shared the same, maybe that's not the case.

**Comment by TGNThump** [comment]
I was trying London

**Comment by qdm12** [comment]
Ok finally fixed it! It was because PureVPN would have bad subdomains listed on their website...

For example `au-sd1-ovpn-udp..pointtoserver.com` which is wrong and should be ``au-sd2-ovpn-udp..pointtoserver.com`.
I fixed it manually and now it works everywhere.

Feel free to let Purevpn know that they should fix openvpn urls. Fixes compared to their website are [here](https://github.com/qdm12/private-internet-access-docker/commit/cb2fe19be3b2c1302fdda6e4695d6887f2950639?diff=split#diff-41b891d556dea812b625a464642e0da2)

Please try again, but it should work from now on.

**Comment by TGNThump** [comment]
That seems to work 👍

**Comment by TGNThump** [comment]
That seems to work. 👍
