### ISSUE TITLE
Feature request: Port forwarding for Vyrpvpn

### ISSUE THREAD

**Issue by qdm12** [qdm12/private-internet-access-docker#196]
- Refers to #181

**Comment by qdm12** [comment]
Hello @Tulip44 what do you mean by port forwarding exactly? Do you mean vpn server side port forwarding, or for example the ability to choose the port [see this](https://support.vyprvpn.com/hc/en-us/articles/360038096291-What-are-the-different-port-settings-). How do you use it currently?

Becauae vyprvpn seem to not really support server side port forwarding although their documentation says they don't and do haha...

Thanks

**Comment by Tulip44** [comment]
Try to explain. Vyprvpn are able to have ports open. Lest say for ftp which
are port 21 or other services different port. So what vpn docker should be
able to do is forward a specific port. A ftp server docker connects trugh
the VPN docker.

Mvh
Even

**Comment by qdm12** [comment]
So you would want clients to connect to your ftp server through <vpn-ip-address>:<some-port> right?

**Comment by Tulip44** [comment]
Think i found out how to run "something" through the vpn container.  "--net=container:other_container" in ssh/terminal when seting up the "server". for some unknown reason portainer gives error when setting it up like that. 
I did set up a test webserver on standard port (80) and it works on vpn public ip and it works :)

**Comment by qdm12** [comment]
Actually, are you running with `FIREWALL=off`? Because the firewall should block access I think.... well it should haha. Let me know, I'll adapt the code and variables such that you can specify ports you want to allow (and block incoming ports we don't want).

**Comment by qdm12** [comment]
It's done 🎉  If you want to use for example ports `9000` and `9001` such that you can access them at <vpn-ip>:9000 and <vpn-ip>:9001, set the environment variable `-e FIREWALL_VPN_INPUT_PORTS=9000,9001`. I tested it with your credentials and it works as far as I can tell. Thanks!

**Comment by qdm12** [comment]
Hey @Tulip44 is port forwarding still working on VyprVPN? Their documentation suggests it's not really there anymore. We're wondering for #337

Thanks!

**Comment by Tulip44** [comment]
> Hey @Tulip44 is port forwarding still working on VyprVPN? Their documentation suggests it's not really there anymore. We're wondering for #337
> 
> Thanks!

Hmm not sure, i use mullvad with wireguard for now lol. much better performance compared to openvpn, now it max out my fiber  👯‍♀️ Mullvad do support portforward to.

**Comment by qdm12** [comment]
alright thanks for the reply. I'm working on a wireguard implementation these days, I'll try to ping back here once it's ready if it can interest you 😉
