### ISSUE TITLE
Feature request: Forwarded port returned via built-in HTTP server

### ISSUE THREAD

**Issue by twistedsanity** [qdm12/private-internet-access-docker#202]
1. What's the feature?
Add ability to return currently forwarded port via the built-in HTTP server.

2. Why do you need this feature?
I am trying to automate the update of port forwarded in other apps/containers and a simple value returned via a http source is a lot easier to integrate into other solutions. Often direct file access in the current solution is not suitable.

(Hope this is a fair request, and thank you for such an awesome solution and all the work put in.)

**Comment by qdm12** [comment]
That's a great idea, I'll do it soon! Quick question out of the topic, how are you using port forwarding? I can't figure out how to test it actually (trying with netcat, nmap, http servers nothing seem to work).

**Comment by qdm12** [comment]
Hello, you now have an http route where you can for example:

```sh
wget -qO- http://<your-docker-host-ip>:8000/openvpn/portforwarded | jq .port
```

To get the port forwarded only. This requires jq installed (i.e. `apk add jq` on Alpine).

If you can also **answer** the question above about how you use port forwarding please? I'm trying to test it but it doesn't seem to work so far for me (no use for it, but it would help to test things for users). Thanks
