### ISSUE TITLE
arm32v6 image 10/12 error

### ISSUE THREAD

**Issue by Frepke** [qdm12/private-internet-access-docker#23]
Try to build an arm32v6 image, but step 10 from 12 ends with an error:

Step 10/12 : COPY unbound.conf /etc/unbound/unbound.conf
COPY failed: stat /var/lib/docker/tmp/docker-builder788567986/unbound.conf: no such file or directory.

kr.,
Frepke

**Comment by qdm12** [comment]
Hi Frepke,

Sorry about that. I fixed the instructions in the readme and it works now. Yours should be:

```sh
docker build -t qmcgaw/private-internet-access https://github.com/qdm12/private-internet-access-docker.git -f Dockerfile.arm32v6
```
