### ISSUE TITLE
Automatic reconnection

### ISSUE THREAD

**Issue by JesterEE** [qdm12/private-internet-access-docker#26]
I used PIA for a long time with the Windows client application and found the connection to many servers to be less than bulletproof. On a 24/7 uptime machine, I typically logged 2-3 disconnects/day. I took a look at your script and the openvpn client config files from PIA and I see no mechanism for reconnecting when the connection fails. Is it there and I missed it?

I'm interested on tracking where this docker goes. Especially with the items you are adding for the future improvements (+1 port forwarding support 😁)

**Comment by qdm12** [comment]
Hi there,

Reconnects are out of my control, and openvpn should reconnect by itself if it's running as root. If openvpn fails, there is always the Docker restart option that can be set to `always`. Why are Reconnects bothering you? I could indeed put the openvpn command in a while loop if that's what you mean?

I should add port forwarding soon, I'm planning on upgrading the container to the latest Alpine 3.10 like today.

**Comment by JesterEE** [comment]
If openvpn does the reconnecting by itself by default there is no issue. I did some reading and thought this wasn't the case without a server side directive that we don't have control over (and don't necessarily know if PIA issues on their side). I may be mistaken and I hope I am. So, yes, I was expecting to see the openvpn connection in some endless detection/reconnection loop, but this may not be necessary. I started a connection on my always on server and will monitor the logs to see what happens over a week or so.

Off topic, binhex has done a great job implementing openvpn connections in a lot of their containers. For me, since they are based on arch, I believe they tend to be a bit more bloated memory-wise then they probably need to be. Have you had a look at his work? Specifically https://github.com/binhex/arch-int-openvpn and https://github.com/binhex/arch-delugevpn.

**Comment by qdm12** [comment]
I don't really understand the problem you're trying to tackle yet. There are indeed reconnections like about once every 3-4 days, but Openvpn seems to handle them, and the container does not restart.

I would be interested in knowing more about your issue as I'm concerned in making this image the best for PIA :+1:

**Comment by gurabli** [comment]
I use this PIA docker for a long time and never had any problems with reconnecting. I think PIA handles this on server side, but I can't confirm this. What I know, that on dropped connection, it is reconnecting fine, never had to do it manually.

This IS the best PIA docker, you are doing an amazing work here!

**Comment by qdm12** [comment]
Hi @JesterEE I will close the issue for now, feel free to re-open it if you would like to comment about your logs and/or reconnections.

**Comment by JesterEE** [comment]
As a follow-up, I got a bunch of disconnections today, and the container handles reconnecting well.  It waits 1 minute for TLS to negotiate, and if it fails, attempts to restart/reconnect immediately.  See the log: https://pastebin.com/wA5nyhac

I did not test any IP leaking during the downtime, but judging from the firewall rules that are being applied, I doubt there is any need for concern.

:shipit:

**Comment by qdm12** [comment]
Hi thanks for the follow up! The reconnection works well although it's a bit slow, so not ideal for 100% uptime unfortunately. I'll look into it maybe there are openvpn settings to reconnect faster.

**Comment by JesterEE** [comment]
This may not be something that is under our control; it may be set by the server. But ... I dug a bit and found the ```–hand-window n``` directive. This defaults to 60 (seconds) and is not set in the PIA openvpn client config files. We _may_ be able to set it either in the file or on the command line and have it override the default if the server does not impose it's own.

**Comment by JesterEE** [comment]
Though, if 100% uptime is what you're after, decreasing the TLS negotiation window might not be the right approach.

If the disconnect is due to the client being offline obviously, there's no VPN connection happening anyway.

If the servers offline, no amount of connection attempts is going to solve that.

Maybe a roll over server connection setting would be more appropriate, where the user selects a backup server to connect to if the first one fails to connect for a set period of time. So instead of setting one server to connect to, the user sets a priority list of servers to connect to.

**Comment by qdm12** [comment]
So regarding backups, openvpn should try the next IP address the PIA server hostname resolved to (usually ~10 addresses).

You can mess around with openvpn by passing it arguments using the Docker command as the final entrypoint script line is `openvpn --config config.ovpn "$@"`. Let me know what you find out! :smile: 

PS: I'm travelling these days so cannot really test things unfortunately.

**Comment by qdm12** [comment]
Hey @JesterEE I think you were talking about doing an unraid template for my container back in 2019, there is one existing which is quite outdated; are you the author by any chance? I don't run Unraid myself and their app system seems a bit closed off, would there be any way to suggest changes? Thanks!
