### ISSUE TITLE
Can't resolve PIA hostnames

### ISSUE THREAD

**Issue by parker789** [qdm12/private-internet-access-docker#27]
Hey,

Sorry if this is such a dumb question.. but my networking background is slim to none. I'm new to the realm of docker and trying to become my own network admin.  I have this docker container running on my local server, but I can't resolve any of the PIA hostnames.  Could you shed some light on exactly what's meant by allow outgoing TCP 453 to 1.1.1.1, and what I need to do to configure that? Also, could you shed some light on the configuration of the proxy so I'm able to access this on my local network?

**Comment by qdm12** [comment]
Hi there,

Allowing TCP 853 (not 453) for example is needed if you use your host system firewall such as `iptables` or `ufw` or another external router with complex options. If you just use a simple router with port forwarding, no need to worry about it!

You don't really need a proxy anymore I believe, just add your local network subnet (i. e. `-e EXTRA_SUBNETS=192.168.1.0/24` or `-e EXTRA_SUBNETS=192.168.1.6,192.168.1.8`) to the container. All the readme instructions are then hopefully clear enough depending on what you want to achieve.. by the way what do you mean by *access this on my local network*? HTTP proxy? Published ports?

**Comment by Frepke** [comment]
I  can confirm the proxy isn't necessary anymore.

**Comment by parker789** [comment]
Hey, thanks for the quick replies! Sorry, 853 yeah ;) So I haven't set up any `iptables` or `ufw` rules, but I'm running an `OMV` image (https://www.openmediavault.org/) - so they may have some things which are set by default.

Based on what you said it seems that I should be able to connect, so I'll check the default rules for `iptables` / `ufw` when I get home. For accessing this on my local network, I was talking about the HTTP proxy. I'd like to run other containers using this as a network, and then view their web pages on my local subnet (`192.168.1.0:<port>`)

**Comment by Frepke** [comment]
>Hey, thanks for the quick replies! Sorry, 853 yeah ;) So I haven't set up any `iptables` or `ufw` rules, but I'm running an `OMV` image (https://www.openmediavault.org/) - so they may have some things which are set by default. ...

@parker789 

I'm also running a OMV image on my Odroid HC1. 
When you launch the pia container you have to publish the ports you wanna use for de webinterface from the linked containers. For nzbget you should publish port 6789 (-p 6789:6789/tcp). When the pia container is running you can launch the nzbget container with** —net=container:pia**. When both containers are running you can connect to the nzbget webinterface with http://lan-ip:6789. 

Kr.,
Frepke

**Comment by parker789** [comment]
@Frepke 

Thanks for the tips! So that's what I've expected, but somehow I need to resolve this pia hostname issue first. Did you have any issues with OMV's default firewall rules and the dns resolver?

**Comment by Frepke** [comment]
>@Frepke  ...

@parker789 

now you mention, it is possible that I've forwarded port 80 and/or port 443 in my router for your problem. I'm not 100% sure, but I think I had the same problem once. 

Try to forward port 80 and if that doesn't help try port 443. 

Good luck 
Frepke

**Comment by parker789** [comment]
👍 will do - thanks

**Comment by qdm12** [comment]
Note that the pia container and your other containers should be in the same Docker network for their names to get resolved properly, maybe that was your issue?

**Comment by Frepke** [comment]
> Note that the pia container and your other containers should be in the same Docker network for their names to get resolved properly, maybe that was your issue?

I thought parker789 meant that when running the pia container, the logfile gave an error while: Detecting IP addresses corresponding to ca-montreal.privateinternetaccess.com...
The container couldn't find IP addresses and will try again.

But maybe I wrong :(

kr.,
Frepke

**Comment by qdm12** [comment]
Hi Frepke, where did you hear this? I cannot see this error mentioned by parker789 anywhere...

**Comment by parker789** [comment]
Hey, Frepke is correct. My docker container log gave me an error detecting the hostnames for my pia server. 

As for the pia container and other containers being in the same Docker network, i'll check into that! I was able to run `docker run --rm --network=container:pia alpine:3.10 wget -qO- https://ipinfo.io` but this just returned my host's IP and not the VPN's

**Comment by Frepke** [comment]
>Hi Frepke, where did you hear this? I cannot see this error mentioned by parker789 anywhere...

@qdm12 
Sorry, didn't read it anywhere :( 
It was my interpretation of the problem because it looks to me the container wasn't running error free. I had this issue once before. 

Kr.,
Frepke

**Comment by qdm12** [comment]
@Frepke woah good job guessing the problem then !! I thought it was something completely irrelevant on my side...

@parker789 would you mind sharing the output of `docker logs pia` ?

If any error occurs during PIA initialization (including the first hostname resolution), the whole container should fail (hopefully!)

**Comment by parker789** [comment]
@qdm12 i'll get back to this when i get home tonight. i believe the state of the container is stuck in "Starting" though

**Comment by gurabli** [comment]
I'm having a same problem now:
nslookup: can't resolve 'swiss.privateinternetaccess.com': Try again
In the logs.

It was working fine few days ago, nothing changed on my system.

**Comment by qdm12** [comment]
That's odd 😞 
Have you tried with other regions? Does it fail for all of them, some of them or just one?

One quick fix would be to have an env variable to not translate the domain name `swiss.privateinternetaccess.com` into IP addresses but then the firewall could not restrict outbound VPN traffic to only these IP addresses 😭

**Comment by qdm12** [comment]
Oh never mind, I just pulled the latest PIA and it does not work as well. Let me see what I can do!

**Comment by gurabli** [comment]
Thanks for looking into this, hope you can fix it soon.

**Comment by qdm12** [comment]
Yes it's just a DNS issue, turning `DOT=off` should solve it for now, but I am investigating.

**Comment by gurabli** [comment]
> Yes it's just a DNS issue, turning `-e DOT=off` should solve it for now, but I am investigating.

I can confirm this, setting DOT=off and BLOCK_MALICIOUS=off makes it work again. I would guess it is somewhat related to DOT option as this is new, I had BLOCK_MALICIOUS=on for long time, but no DOT in docker-compose.

**Comment by qdm12** [comment]
Ok so it's because of `BLOCK_NSA=on` on my side. This is because the list is built every 3-4 days and the PIA image is updated with the new list every 3-4 days. The PIA hostname probably got included for whatever reason, I'm checking on that. Would you mind trying with `DOT=on` and `BLOCK_MALICIOUS=on` but `BLOCK_NSA=off`? Thanks !

**Comment by qdm12** [comment]
Hi @parker789 @gurabli @Frepke thank you all for your help!

In the end I have re-launched a build of the block lists (especially the NSA one), rebuilt the Docker image and it now works with `DOT=on`, `BLOCK_MALICIOUS=on` and `BLOCK_NSA=on` as well. I have also tested it with the image from Docker Hub which works too.

If you have any trouble, don't hesitate re-opening this issue.

**Comment by Frepke** [comment]
Thank you too.

Kr.,
Patrick

**Comment by parker789** [comment]
Nice! thanks for the help. I'm back to trying to get things setup again :)

**Comment by parker789** [comment]
@qdm12 

I'm going to piggy back on this just as I'm learning.. and no need to flood your project with question issues.

I have things up and running with a second container `linuxserver/rutorrent` connecting through the pia container. The ip address of both `pia` and `rutorrent` containers are both going through the VPN. nice!

Now.. the problem is i still can't access the rutorrent web-ui from my local host ip (192.168.1.10). rutorrent by default uses port 80 for the web-ui, which is obviously used by HTTP, and is already being used on the host machine for my OMV admin ui.  From my understanding, I should add something like `-p 803:80/tcp` on the pia container to view the rutorrents web-ui (port 80) from my host ip @ 192.168.1.10:803? I'm missing something because this does not work. any help would be appreciated! :)

**Comment by gurabli** [comment]
Thanks @qdm12 for fixing this issue so fast!
Will check with everything blocking related enabled this evening.

**Comment by Frepke** [comment]
>@qdm12  ...

@parker789 

Yes, publishing the ports that way is okay. Unfortunately port 803 isn't allowed, you have to choose a number higher than 1024. 

Kr.,
Frepke

**Comment by qdm12** [comment]
I think port `80` should be free on the PIA container's network stack and you should be able to map to the port of your choice on your host as long as it's free. 

Maybe try with `-p 8080:80/tcp`? Ideally, you may want to avoid using ports below 1024 as these are privileged ports and might give you permission issues.

**Comment by parker789** [comment]
Awesome guys! @Frepke @qdm12  thanks a lot for the help. I think in the end my `EXTRA_SUBNETS=192.168.1.10` was bad and needed to be `192.168.1.0/24` - everything is working though :)

**Comment by qdm12** [comment]
if your desktop is for example `192.168.1.12` you could only add `192.168.1.12` to `EXTRA_SUBNETS` and not the entire subnet `192.168.1.0/24`. But if you're lazy like me and just want to allow your whole LAN to access it, use the entire subnet!

By the way, side note, **do not** port forward to the HTTP proxy from outside your home network as the connection is, I believe, unencrypted, although it will work.

**Comment by parker789** [comment]
I had the exact ip added to `EXTRA_SUBNETS` at first, but then switched it and things started working. I changed some docker port settings at the same time though, so it was probably the port settings which actually fixed things.

Also, yeah thanks! I do need to come up with a solution to access all this outside my home network, but that's for another time
