### ISSUE TITLE
Proxy question

### ISSUE THREAD

**Issue by gurabli** [qdm12/private-internet-access-docker#28]
I see that proxy is on port 8888 which is the default port for oscam. I have two questions:
1) is it possible to change proxy port number with env variable? 
2) is dns routed over the proxy too in order to prevent any IP leaks?

**Comment by qdm12** [comment]
1. You can now use the environment variable `PROXY_PORT` to set tinyproxy's port.
1. To verify this, I have set my DNS on my computer to some non existent LAN IP addresses so my internet would no longer work. When going through the proxy, it would work meaning the DNS is routed through the proxy, which itself forwards the DNS traffic to Unbound (`127.0.0.1` from its point of view) which forwards it to 1.1.1.1 over TLS.

**Comment by gurabli** [comment]
I can't stop repeating myself, you are doing some real amazing job here. This is certainly the best VPN docker available.
I will test it tonight and report back.
