### ISSUE TITLE
Replay warning

### ISSUE THREAD

**Issue by burkasaurusrex** [qdm12/private-internet-access-docker#34]
I'm getting a lot of the following error:

`Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #18292 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings`

Doesn't appear to be affecting functionality, but thought I'd pass it along. I'll get a new warning about every minute.

**Comment by qdm12** [comment]
Hi there,

You might want to try with the new image

```sh
docker image pull qmcgaw/private-internet-access
```

I have reduced the size of packets to 1300 (instead of 1420 I believe) so it might work without the bad packet ID. This warning is usually due to torrenting which generates packets too large to fit in the VPN tunnel apparently. Re open the issue if you still get this warning.

**Comment by Frepke** [comment]
Hi,

The problem is still there with torrents in the new image (ARM).

kr.,
Frepke

**Comment by qdm12** [comment]
Hi, can you try with the command `--tun-mtu 1300 --fragment 1100 --mssfix` ? In docker-compose, use `command: --tun-mtu 1300 --fragment 1100 --mssfix`. Although not a solution, you can use the command `--mute-replay-warnings` to mute these warnings.

**Comment by Frepke** [comment]
When running this command:

docker run -d --init --name=piavpn_US --cap-add=NET_ADMIN --device=/dev/net/tun --tun-mtu 1300 --fragment 1100 --mssfix -p 9191:8888/tcp -p 6881:6881 -p 6881:6881/udp -p 9505:9505 -e REGION="CA Montreal" -e PROTOCOL=udp -e ENCRYPTION=strong -e EXTRA_SUBNETS=192.168.1.0/24 -e PORT_FORWARDING=true -e PROXY=on -e PROXY_LOG_LEVEL=Critical -e DOT=on -e BLOCK_MALICIOUS=on -e BLOCK_NSA=on -e USER=x4967298 -e PASSWORD=iffkeHKL3r --restart unless-stopped qmcgaw/private-internet-access:latest

there's an error: unknown flag: --tun-mtu

kr.,
Frepke

**Comment by qdm12** [comment]
Hi @Frepke 

You need to pass the arguments as commands to the Docker container (which gets forwarded to openvpn), so after the Docker image name `qmcgaw/private-internet-access:latest`. This should do:

```sh
docker run -d --init --name=piavpn_US --cap-add=NET_ADMIN --device=/dev/net/tun \
-p 9191:8888/tcp -p 6881:6881 -p 6881:6881/udp -p 9505:9505 \
-e REGION="CA Montreal" -e PROTOCOL=udp \
-e ENCRYPTION=strong -e EXTRA_SUBNETS=192.168.1.0/24 \
-e PORT_FORWARDING=true -e PROXY=on \
-e PROXY_LOG_LEVEL=Critical -e DOT=on -e BLOCK_MALICIOUS=on \
-e BLOCK_NSA=on -e USER=x4967298 -e PASSWORD=iffkeHKL3r \
--restart unless-stopped qmcgaw/private-internet-access:latest \
--tun-mtu 1300 --fragment 1100 --mssfix
```

Sorry I cannot test it myself, I am on the move and can't really monitor my logs right now.

**Comment by Frepke** [comment]
Hi Quentin,

--tun-mtu 1300 --fragment 1100 --mssfix doesn't solve the problem for now I'm using --mute-replay-warnings so the log will be clear.


kr.,
Frepke

**Comment by qdm12** [comment]
Yes but I'm not sure of the configuration file takes precedence on the flags provided.

I'm setting up my server now so I should be able to play around with openvpn to fix this.

**Comment by qdm12** [comment]
Hi all, looking at [this issue](https://github.com/haugene/docker-transmission-openvpn/issues/257), it seems the problem comes from UDP indeed and cannot be avoided unfortunately. It is not a problem security wise, so I will simply add `mute-replay-warnings` to the default configuration file to stop the logs spam.
