### ISSUE TITLE
Issues starting on a raspberry pi

### ISSUE THREAD

**Issue by chazragg** [qdm12/private-internet-access-docker#35]
when i run your docker-compose on my Rpi3 B and received an error saying "unsupported config option for service.pia 'init'" i have altered all of the correct variables to suit my needs

i also tried using the docker run command which does start the container but it closes off straight away and the logs read "ERROR: Could not load module /lib/modules/tun.ko: no such file or directory"

any help would be appreciated.

**Comment by chazragg** [comment]
Ok, so I realized i was not building an arm image so that is on my part but I am still having issues using docker-compose to run the container?

**Comment by qdm12** [comment]
Hi there,

Did you follow the [setup instructions](https://github.com/qdm12/private-internet-access-docker#setup)?

- You need to install the tunnel kernel module, probably with `modprobe tun`
- In your docker-compose, you should have `init: true`, see [this](https://github.com/qdm12/private-internet-access-docker/blob/master/docker-compose.yml#L12). Maybe upgrade your Docker and Docker Compose if it does not work.

**Comment by chazragg** [comment]
i managed to get it working by removing the init:true and i believe the docker-compose is running at the highest it will update to.

Thank you for the help

**Comment by qdm12** [comment]
What's the docker-compose.yml version defined? It should be `version: "3.7"`. The init is important as killing the container may leave some zombie processes (Unbound or tinyproxy) behind that you would only be able to remove by rebooting your machine.

**Comment by chazragg** [comment]
so i originally had the the compose set to version 3, setting it to 3.7 has not stop it erroring at init: true but now it errors at the command: line

**Comment by qdm12** [comment]
What's your command?
Would you mind sharing your *docker-compose.yml*? Don't forget to remove your credentials from it.

**Comment by chazragg** [comment]
it is a straight up copy of your docker-compose example with my PIA creds, config volume change and also some extra ports for other containers. 

so the command: is just empty, i have not used command before so was not really sure if i had anything extra to add

**Comment by qdm12** [comment]
You can remove the line then, sorry if I left it empty in my docker-compose.yml, it should contain something or not be there at all. These are extra flags you can pass to openvpn, and it's the same as a command you would give after the image name in a `docker run` command.

Regarding the `init: true`, I'll try on a raspberry pi I have to see if it works. What's your Docker and docker compose versions?

Would you mind trying

```
docker run -it --rm --init alpine:3.10
```

see if it gives an error? Thanks

**Comment by chazragg** [comment]
init is running fine now, i changed the docker-compose version to 3.7 and it all worked (your template uses version 3)

`docker run -it --rm --init alpine:3.10`
give me no errors just a command line for the container

all is working as i would expect now. there is a couple issues but i will raise them in their own ticket if needed

**Comment by qdm12** [comment]
Great! I'll update the docker-compose now, sorry for the confusion. Please do create issues, I'll be happy to look into it.

**Comment by chazragg** [comment]
no worries, these things happen. command and init and just two more things to add to my learning list :p 

Thanks for the help, much appreciated

**Comment by qdm12** [comment]
Just a little heads up 😺 There is now images built for all architectures automatically, and you can pull them with `docker pull qmcgaw/private-internet-access`, Docker will pick the right image for ARM under the hood 👍

**Comment by chazragg** [comment]
that is awesome, saves me a couple of lines in my compose file.

keep up the good work!!!
