### ISSUE TITLE
Password environmental value

### ISSUE THREAD

**Issue by TXJustin** [qdm12/private-internet-access-docker#38]
If the environmental value for PASSWORD contains a dollar sign ($), authentication with Private Internet Access will fail.  The generated /auth.conf will not contain the correct password - it will be truncated at the dollar sign.

For example, if your pia account password is:  **B1g$ecret**   the generated auth.conf will list only **B1g**

Host: Ubuntu 18.04 LTS
DockerCE 19.03

**Comment by evilhamsterman** [comment]
This is an issue with how shells handle special character. A simple fix is you can put a \ before the dollar sign in you password. This should be documented in the README

**Comment by qdm12** [comment]
Hi @evilhamsterman thanks for replying, I was quite busy recently.

It is indeed the shell's fault I'll try to find a way to automatically escape `$` for this case.

**Comment by qdm12** [comment]
I cannot really find a universal solution to escape special characters unfortunately. I would be happy to know if someone finds one. So for now just prefix special characters such as `$` by `\`.

**Comment by evilhamsterman** [comment]
I'm not aware of anyway, because of that you should document in the README the need for escaping characters.

**Comment by TXJustin** [comment]
Thanks for taking the time to look into this.

**Comment by qdm12** [comment]
Actually in the end, it seems feasible with [a sed command](https://stackoverflow.com/questions/15783701/which-characters-need-to-be-escaped-when-using-bash/20053121#20053121). I will implement it soon.

**Comment by qdm12** [comment]
Hi @TXJustin 

Does escaping the `$` sign with `\` (i.e. `-e PASSWORD=mypa\$\$word`) work? I am trying to automate it with a string replacement, but it does not seem to work so I will add it to the readme only.

**Comment by qdm12** [comment]
A little side note, it now works with any character in the 'beta' Docker image `qmcgaw/private-internet-access:go` where there is no more shell scripting 👍
