### ISSUE TITLE
HTTPS reverse proxy

### ISSUE THREAD

**Issue by gurabli** [qdm12/private-internet-access-docker#4]
Great work! I'm new to Docker, learning things now. I have a non-docker home server configured the very same way, but thinking about migrating to Docker.

I'm missing nginx with Let's Encrypt certificates for reverse proxy. Do you think it is possible?
Btw, why not use /deluge instead of port number in nginx?

**Comment by qdm12** [comment]
Hi gurabli! I am actually using Caddy which does the let's encrypt part by itself and is easier to use than Nginx in my opinion. The Nginx container I have is only used as a reverse proxy to access other containers using the PIA container. I then use Caddy server to proxy paths like deluge to a port number.

Also note that some web UI such as deluge's one are not nice with additional root paths (for css paths and so on) so you should keep it to a port number / subdomain name and not a path (i.e. https://deluge.yourdomain.com or https://yourdomain.com:9999, not https://yourdomain.com/deluge)

**Comment by qdm12** [comment]
Mistyped an issue number... My god, this has been a long journey 🤣
