### ISSUE TITLE
network_mode: "container:pia" in swarm mode

### ISSUE THREAD

**Issue by chazragg** [qdm12/private-internet-access-docker#40]
let say i have two devices setup in docker swarm each device has the following:

Device one, PIA
Device two: Torrent client

is it possible to use network_mode: "container:pia" to router traffic from device two through the container on device one or would i have to run PIA on the same device as the container i am trying to force through the VPN ?

**Comment by qdm12** [comment]
I have no idea to be honest on Docker Swarm, but it might work if 2 containers can detect each other when on two hosts in a docker swarm configuration.

Let me know if it works out!

Otherwise you could use the tinyproxy for now although it's not the best it works decently. I'm trying to find another way (probably a SOCKS5 proxy) to tunnel tcp and udp traffic.

**Comment by qdm12** [comment]
Hi there,

You can now try with Shadowsocks, I just added support for it. It's a SOCKS5 proxy that tunnels both UDP and TCP so you could connect to PIA from other devices/containers. It's straightforward to setup a Windows/Android/OSX etc. client with a GUI and relatively simple to setup a Linux client without a GUI too, so that could work for connecting a container on device 1 to PIA on device 2.

For example, my PIA container runs on my server; my desktop is connected system wide to PIA through Shadowsocks,; my Android phone has certains apps going through the PIA container.

**Comment by coreshift** [comment]
"For example, my PIA container runs on my server; my desktop is connected system wide to PIA through Shadowsocks,; my Android phone has certains apps going through the PIA container."

Could I create an entire lan segment that way? Something I've been trying to do is create a LAN behind PIA (just using iptables on the host machine, not your Docker), but also be able to have access to another LAN segment that has direct access to the internet. i.e create 192.168.2 behind PIA through an ethernet port and it's own DHCP server, that can also communicate with 192.168.1 that has internet access. But for the life of me I can't get the iptables crap working right.

**Comment by chazragg** [comment]
how would this work fro ma docker container running on another device ?

**Comment by qdm12** [comment]
The easiest would be to install a shadowsocks client in your container and connect to PIA through its Shadowsocks server.

**Comment by chazragg** [comment]
i will take a look into this. thank you for the update.

**Comment by chazragg** [comment]
Hey, quick question. i think i have found a way to do the above using the service. but i am having another issue.

when I try to deploy the PIA container using swarm I get an error saying that each of my raspberry pis other than the master is an unsupported platform. but the weird thing is is that i can go to each pi and manually deploy the container on its own and all works fine. 

i am not at home currently but i can get some logs and screenshots when i am back later.

**Comment by qdm12** [comment]
Hello, oh you made it work with a shadowsocks client?

Can you send me the error message? Does it work if you build the image yourself? And, out of curiosity, why running pia in on multiple devices :thinking: ? Thanks

**Comment by chazragg** [comment]
so no I was not using shadowsocks client I thought of another way to do what I was trying to achieve. 

i'll send you an error message shortly i originally build the images my self on each pi as this was tested before you made your recent changes to have it automatically build an arm image and i can run them fine if I use the docker-compose file but when i try to stack deploy the same docker-compose I get the unsupported platform message. i am just about to leave work so I will jump on that when I get back 

and it is not so much running on multiple devices more for replication when one client dies I don't really have a need for it just toying about and learning new things. i suppose real-world use would be cpu utilization for multiple PIA clients one Pi could become overloaded with requests

**Comment by chazragg** [comment]
So the error i get from swarm is 
![image](https://user-images.githubusercontent.com/4650060/69681918-87abfd80-10a7-11ea-9826-409519ae3a34.png)

and the container logs seem to all stop at the same line.
![image](https://user-images.githubusercontent.com/4650060/69681931-9abecd80-10a7-11ea-8ca7-22ef09272d6f.png)

but manually running the compose works fine. i think swarm might be ignoring some options within the compose fine which is causing this error.

**Comment by qdm12** [comment]
It looks like it's just not being able to add a route. It tries with `eth2` while docker swarm may use its own interface. I'll remove the error code message so we can see the errors more clearly this evening.

**Comment by chazragg** [comment]
sorry about the delay I started a new SRE position recently and have not had much time to play around. 

I recently took another look into this and it appears the error above only happens when I define an extra subnet to allow through the firewall.

if I removed this from the docker-compose it runs into another error which is:
![image](https://user-images.githubusercontent.com/4650060/71787526-d9359980-3010-11ea-88e6-515db6497074.png)

I have nonroot=no so I am I bit confused as to why it has no permission.

**Comment by qdm12** [comment]
Hi thanks for reporting back. Sorry I didn't have the time to try yet. However from this error message and because you are running as root, it's likely that either you don't give the container NET_ADMIN capability or swarm doesn't work with it.

Are you running the container with ` --cap-add=NET_ADMIN`?

**Comment by qdm12** [comment]
Unfortunately I believe Docker Swarm does not support adding capabilities due to security reasons. See [this issue](https://github.com/moby/moby/issues/25885). So it will be impossible to access the firewall and the tunnel device. :disappointed:

**Comment by chazragg** [comment]
ahh no worries, was a fun learning experience :D

**Comment by jndeverteuil** [comment]
@chazragg, wait a minute here, I'm trying to do the same thing... I used a trick in another circumstance about this issue and maybe we can still work this out for our docker swarms.

We can use https://hub.docker.com/r/ixdotai/swarm-launcher/ to launch a container in a swarm with NET_ADMIN capability... It's not straightforward, but feasable... I'm gonna test it with something like 

```
volumes:
  gluetun:

services:
  vpn-launcher:
    image: ixdotai/swarm-launcher:v0.13.1
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:rw'
    environment:
      LAUNCH_IMAGE: qmcgaw/gluetun:v3.11.1
      LAUNCH_PULL: 'true'
      LAUNCH_PROJECT_NAME: 'vpn'
      LAUNCH_SERVICE_NAME: 'vpn-pia'
      LAUNCH_CAP_ADD: 'NET_ADMIN'
      LAUNCH_ENVIRONMENTS: 'OPENVPN_USER=<user> OPENVPN_PASSWORD=<password>'
      LAUNCH_VOLUMES: 'gluetun:/gluetun'
```
