### ISSUE TITLE
Connecting to containers outside my network

### ISSUE THREAD

**Issue by parker789** [qdm12/private-internet-access-docker#41]
I'm currently using this docker to connect a few other containers to the internet through my VPN using network-container=pia.. one of which happens to be linuxserver/rutorrent. In my rutorrent container i get an error that a port is closed.  I've forwarded the port correctly within my pia container, and i've even forwarded traffic on my router to my servers local ip. am i missing something?

**Comment by qdm12** [comment]
You will need to portforward it on the PIA side, you don't need to do anything on your router. The forwarded port is random and will be displayed in the logs, provided you set `PORT_FORWARDING=true`. The IP address will be the one you have on the PIA server side.

I personally do not need port forwarding for any of my apps so I can't speak of experience however.

**Comment by parker789** [comment]
hey @qdm12 - thanks for the reply.. and sorry for not responding since but i've been out of town. i currently have `PORT_FORWARDING=true` set, but i don't see any information about the ports in my startup log
