### ISSUE TITLE
Port Forward Issue?

### ISSUE THREAD

**Issue by Raph521** [qdm12/private-internet-access-docker#42]
Hi,

I've noticed recently that the portforward.sh script exits with the following error:

```
[INFO] Reading forwarded port,
 * Written forwarded port to /forwarded_port,
[ERROR] Unable to read remote VPN IP, with status 5)
```

I think that the verification to determine the VPN IP is failing due to a failed wget.  I tried the command manually within the container without quiet mode and see the following:

```
/ # wget -O- https://diagnostic.opendns.com/myip
--2019-09-02 01:03:33--  https://diagnostic.opendns.com/myip
Resolving diagnostic.opendns.com... 172.217.13.179, 2607:f8b0:4020:805::2013
Connecting to diagnostic.opendns.com|172.217.13.179|:443... connected.
ERROR: cannot verify diagnostic.opendns.com's certificate, issued by 'CN=DigiCert SHA2 Secure Server CA,O=DigiCert Inc,C=US':
  Unable to locally verify the issuer's authority.
To connect to diagnostic.opendns.com insecurely, use `--no-check-certificate'.
```

Not sure if it's an issue with the region I'm using (CA Montreal).

I tried a different IP lookup domain and it works:

```
/ # wget --timeout=30 https://ipinfo.io/ip -qO -
19x.xxx.xxx.xxx
```

**Comment by Juggels** [comment]
I saw some similar behavior with the CH (Switzerland) region. I have solved it for now by locally adding `--no-check-certificate` to the wget command, but that's more of a workaround than a proper solution of course

**Comment by qdm12** [comment]
Yes it's opendns having trouble with their https certificate (same problem on my project qdm12/ddns-updater). I'll change it to another solution with https to avoid leaking your public ip to an eventual man in the middle.

**Comment by Raph521** [comment]
Thanks, that did the trick!  

Though, I noticed another issue, I'll comment in the appropriate thread about it.

In general, huge fan of the work you've put into this project, thanks!!!
