### ISSUE TITLE
Containers relying on PIA don't recover the network stack when it's restarted.

### ISSUE THREAD

**Issue by coreshift** [qdm12/private-internet-access-docker#50]
Containers using 'network_mode: "container:pia"' lose internet connectivity permanently if PIA is brought down and then restarted. I'm guessing it's because they use the PIA network stack and don't know what to do when it goes away. Any ideas other than having to restart every single container relying on  PIA? I know I can put pia and all the services in one compose file, but that makes for a potentially ridiculously large compose file and a long start time.

Maybe there's a way to send the affected containers a message when PIA starts and have them re-init networking? If not, maybe a way to do a health check for that situation and at least I won't have to restart all the containers manually one by one.

I'm using a linux host and mostly code in Java if that matters.

**Comment by qdm12** [comment]
With @gurabli, we discussed a potential solution to have a Shadowsocks client container connected to the PIA container (so not going through Docker's networking). Other contains could then use that shadowsocks client container as their networking stack in Docker. When PIA reconnects, the Shadowsocks won't disconnect and will smoothly reconnect.

I am working on the instructions to do so, i'll ping back here once it's up. Thanks for your patience!

**Comment by coreshift** [comment]
Awesome! That should increase reliability and reduce restarts a lot. Thank you!

**Comment by qdm12** [comment]
Hello all, do your containers still disconnect occasionally? If so can you share the logs of the pia container? #144 now restarts openvpn from within the container if it fails, so that linked containers don't disconnect (maybe). You can try it out with the Docker tag `:restart` (only for amd64  cpu arch I think).

**Comment by qdm12** [comment]
Closing, see final comment of #108 and pull request #144 

There is no apparent solution to this yet, although, if there is really no Docker networking way to do it, a self updating program inside the container might be the way.
