### ISSUE TITLE
Export the forwaded_port to a variable

### ISSUE THREAD

**Issue by groenator** [qdm12/private-internet-access-docker#52]
Hi,

I am using your image with Deluge container, the downside that I have with deluge container is that I have to set the incoming port for torrenting manually. Since I have to wait for PIA image to write down the forwarded_port first, I can't set the port. After I have to port from the file I have to manually set the port in the UI and restart the container. 

I tried many things to export this port to a variable and pass it to deluge, but so far I didn't have any luck.  Is it possible to export the forwarded_port to a variable instead of a file? Or, at least export the port to a file and variable. If I have a variable would be easier to pass the port to other containers, such a deluge. 

What is the best way to pass the port to another container, other than mounting the volume?

Thank you!

**Comment by qdm12** [comment]
I can export it to an environment variable inside the PIA container but it won't be available to other containers.

Plus PIA servers decides of the forwarded port so we can't preset a variable.

The only solution is therefore to write it to file. You could bind mount it and share it across containers like that. You could modify the Deluge container to read the file at start, in example:

```sh
MYVAR=`cat /yourpath/portforwardfile`
# then write it to your deluge conf file with sed for example
```

**Comment by groenator** [comment]
Hi,

Doing what you have described it doesn't work at all. I have created a new
var in my docker-compose file, which will cat the file but when I ssh into
the container and run export -p. Instead of reading the port from the file
it does show exactly the path of where my file is located. So for
some reason, it doesn't execute my command.

export PGID='1000'
export PIA_PORT='`cat /forwarded_port`

I have three containers running in the same docker-compose file. Creating a
var to read the port from  PIA container will make it easy for deluge to
read the env if I use a .env file set to PIA_PORT=${PIA_PORT}, and set this
in the environment section of docker-compose for deluge container.

I've tried every possibility, I can share my docker-compose file with you.
If you have a better solution please let me know.

Regards,

**Comment by qdm12** [comment]
I'm not sure what you're doing, maybe share your docker compose file? Take care of removing your credentials.

The way I would do it is
- have a shared volume between all the containers, probably set the port forward file to be in another directory like `/forward/portfile` and have a Docker volume at `/forward`
- modify the Deluge image by adding an export or sed command before its entrypoint.

**Comment by groenator** [comment]
Hi,

Here is a copy of my compose file. As it shows, I am exporting the volumes
and make the volumes available between containers. I will look at the entry
point, do you have any guides on how to do it? Do I have to rebuild your
image again?

version: '3'
services:
  vpn:
    container_name: deluge_vpn
    image: qmcgaw/private-internet-access
    hostname: deluge.wonkypaw.org
    restart: always
    ports:
      - "8112:8112/tcp"
      - "80"
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    networks:
      vpn:
        ipv4_address: 172.20.0.11
    volumes:
      - /data/infra/deluge/forwarded_port:/forwarded_port
      - /etc/localtime:/etc/localtime:ro
    environment:
      - USER=user
      - PASSWORD=pass
      - ENCRYPTION=strong
      - protocol=udp
      - REGION=DE Frankfurt
      - NONROOT=no
      - DOT=on
      - BLOCK_MALICIOUS=on
      - BLOCK_NSA=on
      - FIREWALL=off
      - EXTRA_SUBNETS=192.168.1.0/24,10.8.0.0/24
      - PORT_FORWARDING=on
  deluge:
    container_name: deluge
    image: linuxserver/deluge
    restart: always
    depends_on:
      - vpn
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK_SET=022
      - TZ=Europe/London
      - PIA_PORT=`cat /forwarded_port`
    network_mode: "service:vpn"
    volumes:
      - /data/torrents/deluge/config:/config
      - /nfs/download/torrents:/downloads
      - /data/infra/deluge/forwarded_port:/forwarded_port
  nginx:
    container_name: deluge_nginx
    image: nginx
    restart: always
    network_mode: "service:vpn"
    stdin_open: true
    tty: true
    depends_on:
      - vpn
    volumes:
      - /data/infra/nginx/deluge:/etc/nginx/
networks:
  vpn:
    external: true

**Comment by qdm12** [comment]
A slightly better way would be to have a named volume as `- portforward:/forwarded_port`.

You need to change the entrypoint of linuxserver/deluge, you could use the `entrypoint` command to overwrite it in Docker Compose for your Deluge container. You'll have to dig through linuxserver's deluge image as their entrypoint seems quite hidden to me. Or use another Docker image for Deluge.

**Comment by qdm12** [comment]
Please have a look at #53 it should indirectly solve the issue. I'll close here for now.

**Comment by groenator** [comment]
Sweet, thank you.
