### ISSUE TITLE
Add other services to container

### ISSUE THREAD

**Issue by gurabli** [qdm12/private-internet-access-docker#54]
Hi @qdm12 I would need a non-standard container for my specific need, but I'm not sure how to do this. It is highly against docker principles, but still would be a good solution to my use case.
And I also have an idea where a container like this could largely contribute to another project. Anyway, can we get in contact over email to discuss this since this is not so much related to this container. Thanks!

**Comment by qdm12** [comment]
My email is quentin.mcgaw@gmail.com or +13474502562 for Whatsapp for quicker replies :+1:
