### ISSUE TITLE
/etc/unbound/blocks-malicious.conf:2: error: newline inside quoted string, no end "

### ISSUE THREAD

**Issue by jeliasson** [qdm12/private-internet-access-docker#56]
Since the last update, I get this in stdout. By any chance this is a result of commit [e8300f1](https://github.com/qdm12/private-internet-access-docker/commit/e8300f123f636034142dbc2b8aec1f0c74e8a41f)?

```
[INFO] /auth.conf already exists
[INFO] 8146 NSA hostnames blacklisted
/etc/unbound/blocks-malicious.conf:2: error: newline inside quoted string, no end "
/etc/unbound/blocks-malicious.conf:3: error: stray '"'
/etc/unbound/blocks-malicious.conf:3: error: unknown keyword 'static'
/etc/unbound/blocks-malicious.conf:4: error: syntax error
read /etc/unbound/unbound.conf failed: 4 errors in configuration file
[1574116078] unbound[57:0] fatal error: Could not read config file: /etc/unbound/unbound.conf. Maybe try unbound -dd, it stays on the commandline to see more errors, or unbound-checkconf
[INFO] Launching Unbound to connect to Cloudflare DNS 1.1.1.1 over TLS...[ERROR] Undefined error, with status 1
```

Thanks!

**Comment by qdm12** [comment]
Hmm, it's line endings problems :(
Last build worked on my Linux server and windows machine, I'll debug it ASAP. Sorry for the inconvenience. I'm going to create release tags tonight too, breaking things has to stop!

**Comment by qdm12** [comment]
Actually I just pulled the image again and it seems to work on my end (with malicious and nsa blocked), would you mind trying pulling it?

```sh
docker pull qmcgaw/private-internet-access
# I assume you use docker-compose 👍 
docker-compose down
docker-compose up -d
docker-compose logs -f
```

**Comment by jeliasson** [comment]
Strange. After a rebuild on my end, it seems just fine. Not really sure what caused that. 

Anyway, if you could tag images that are considered stable it would be great. Thanks for your help and a great image!

**Comment by qdm12** [comment]
It might also be Docker Hub automated builds, I've seen multiple problems as they don't build the images as I build them locally on Arch/Windows for whatever reason. I'm working on moving to Travis CI to build images for all architectures with release tags, I will ping back here once it's done.
