### ISSUE TITLE
AES-NI

### ISSUE THREAD

**Issue by Frepke** [qdm12/private-internet-access-docker#60]
Hi Quentin,

I'm using this container for a while now on an ARM device as you probably know.
For me it's the best PIA container available.

Now I'm testing the container on an different device (HP Thin Client T620 with AES-NI).
Is it possible for the PIA container to use AES-NI?

kr.,
Frepke

**Comment by qdm12** [comment]
I'm not sure if that can be configured on the client side. Looking at the [Openvpn configuration page](https://openvpn.net/community-resources/reference-manual-for-openvpn-2-4/) I cannot find any setting related to AES-NI. It might as well be used automatically as these are CPU instructions set if I'm not mistaken.

Why do you think it's not used?

**Comment by Frepke** [comment]
> I'm not sure if that can be configured on the client side. Looking at the [Openvpn configuration page](https://openvpn.net/community-resources/reference-manual-for-openvpn-2-4/) I cannot find any setting related to AES-NI. It might as well be used automatically as these are CPU instructions set if I'm not mistaken.
> 
> Why do you think it's not used?
> 
> EDIT: It seems to be a kernel module, the only discussion related to it with containers is [here](https://forums.unraid.net/topic/54230-aes-ni-support-in-unraid-docker-containers/) without an answer 😢

Okay thanks,

The doubt was because I expected a bit higher download speed in sabnzbd when the AES-NI instructions were used.

kr.,
Frepke

p.s.
I gonna try a different setup for the T620 without docker to see what the results are.

**Comment by qdm12** [comment]
Maybe try [this](https://stackoverflow.com/a/37160346); completely unsafe if someone hacks your container, it accesses your whole host; but that might work!

**Comment by Frepke** [comment]
> Maybe try [this](https://stackoverflow.com/a/37160346); completely unsafe if someone hacks your container, it accesses your whole host; but that might work!

Thanks,

Looks promising. 
Try it tonight and report it back. 

Kr.,
Frepke

**Comment by Frepke** [comment]
Tried the normal docker setup, afterwards the suggested way as you mentioned before and afterwards the normal installation without docker.

Download speed with sabnzbd in all the cases stuck at approx. 10MB/s.
Maybe this is the max. for the T620 :)

**Comment by qdm12** [comment]
Yes I have a 160MByte/s download and upload internet link but PIA servers usually reaches a maximum of 10MByte/s for me as well. It's probably limited on their side I guess. AES-NI would probably be useful if you do LAN transfers on Gbit networks.

**Comment by Frepke** [comment]
> Yes I have a 160MByte/s download and upload internet link but PIA servers usually reaches a maximum of 10MByte/s for me as well. It's probably limited on their side I guess. AES-NI would probably be useful if you do LAN transfers on Gbit networks.

I think you're right. I've to be more patient when downloading ;)

**Comment by qdm12** [comment]
I'll close the issue for now. Ahh 10MB/s is still better than the 5KB/s I would get years ago :smile:

**Comment by Frepke** [comment]
Okay,
Thanks for your awesome container!!!
