### ISSUE TITLE
Can't connect to containers on service:pia network

### ISSUE THREAD

**Issue by derekslenk** [qdm12/private-internet-access-docker#62]
I have been reading the issues and readme and I can't figure this out.

I have emby connected to service:pia. I did have ports 8096 and 8920 opened up.

I change the emby network_mode to service:pia and get rid of the port forwarding. I then open up the ports on the PIA container but I cannot connect to Emby through the PIA container.

I did the test run to make sure PIA was acutally running and I am getting an expected IP address.

I have my local subnet added as extra: - EXTRA_SUBNET=192.168.12.0/23

However, trying to access the IP of my docker host on port 8096 doesn't work. I am assuming I have the bridge set up wrong compared to my other network I already have?

**Comment by derekslenk** [comment]
Update: I can now access it internally, but now my Traefik rules won't work.

I think I need to redo my whole docker network(s)

**Comment by qdm12** [comment]
Traefik does not work super well with this container unfortunately as I recall. A few other notes:

- port forwarding is only to forward a port on the PIA server side, it has nothing to do with local network
- EXTRA_SUBNETS should be set if you want to directly access the PIA container through for example Shadowsocks. If you want to access another container connected to it (emby) you can leave it blank as the local Docker network of the PIA container is automatically whitelisted
- You might want to try with another network than bridge, bridge can behave a bit differently sometimes.
- You could play around with qmcgaw/port-checker to test a port is accessible (that's what I do).

Good luck! Feel free fo ask more questions.
