### ISSUE TITLE
Weird DNS address

### ISSUE THREAD

**Issue by Frepke** [qdm12/private-internet-access-docker#66]
When I connect my Macbook with the PIA-container trough Outline and I run a dnsleak test, my DNS address is from Cisco OpenDNS, LLC.
DOT=on so it should be a cloudflare address I suppose.

kr.,
Frepke

**Comment by qdm12** [comment]
Hi Frepke,

How are you connecting to the PIA container? Using Shadowsocks?

**Comment by Frepke** [comment]
Hi Quentin,

I'm using Outline for the connection with the PIA container.

**Comment by qdm12** [comment]
What protocol do you use? Socks5? Connecting to the PIA container Shadowsocks server?

It might just be that the Outline client does not support UDP tunneling, which is used by DNS (port 53 UDP). I had to dig around to find a Shadowsocks client that supports UDP tunneling.

**Comment by Frepke** [comment]
> What protocol do you use? Socks5? Connecting to the PIA container Shadowsocks server?
> 
> It might just be that the Outline client does not support UDP tunneling, which is used by DNS (port 53 UDP). I had to dig around to find a Shadowsocks client that supports UDP tunneling.

I tried Shadowsock, now I've a Cloudflare DNS address :)

**Comment by qdm12** [comment]
Oh ok cool then! Yes shadowsocks is pretty nice even out of this container to use a simple VPN (well not VPN, SOCKS5) server. Closing the issue for now.

**Comment by Frepke** [comment]
Thanks for you help!
