### ISSUE TITLE
Update to work as a Kubernetes sidecar container

### ISSUE THREAD

**Issue by npawelek** [qdm12/private-internet-access-docker#68]
Some of the Docker-isms don't fully translate to the Kubernetes realm. I have an incoming PR that will help to adjust the container build allowing this to additionally function as a Kubernetes sidecar. The primary differentiation of using docker with `--net=container:id` and Kubernetes sidecar is that if and/or when the VPN container restarts, the routes and iptables rules applied during the initial start will already exist in the Kubernetes pod. The following aspects required tweaking in order to get this to work (from my experiences):

- `iptables` chains temporarily set to `ACCEPT` prior to performing `nslookup` on the PIA region address.
- Removed forced name resolution via `localhost`. From what I could tell, this only works with DOT mode enabled, as the changes to `resolv.conf` are conditionally set there. Removing the option results in using the default system resolver.
- Added verification step to see if `EXTRA_SUBNETS` routes already exist. Attempting to add an identical route will result in a non-zero exit, causing the container to fail.
- Uncommented proper outbound `iptables` rule for `EXTRA_SUBNETS`
- Generated network/CIDR from the primary interface address using `sipcalc`. Subsequent container restarts were causing the subnet value to be obtained incorrectly using `ip r`.

Also, thanks for maintaining this project! I'm hoping this helps other folks out as well.

**Comment by qdm12** [comment]
Hi there,

I'll look into that very soon. I'm also rewriting the entrypoint in Go (wink wink k8s) in the `go` branch, about 90% done, so your comments will be useful fixing up the routes and firewall setup!

I also had a glimpse at the PR, is it missing some of the modifications mentioned above? Or should I add them myself using your comments? Thanks!

**Comment by npawelek** [comment]
@qdm12 Yep, the bullets initially outlined are all solved in the two associated PR commits.

If you want some help validating things on k8s when your go branch is ready, let me know.

**Comment by qdm12** [comment]
I just added your changes to the Go branch 👍 

The Go rewrite Docker image is now out in 'beta' at `qmcgaw/private-internet-access:go`.

- The documentation is [here](https://github.com/qdm12/private-internet-access-docker/tree/go#private-internet-access-client)
- It should work with the same settings as before
- Feel free to comment here or on the [Slack channel](https://join.slack.com/t/qdm12/shared_invite/enQtOTE0NjcxNTM1ODc5LTYyZmVlOTM3MGI4ZWU0YmJkMjUxNmQ4ODQ2OTAwYzMxMTlhY2Q1MWQyOWUyNjc2ODliNjFjMDUxNWNmNzk5MDk)

**Comment by qdm12** [comment]
I (finally) merged my 2 months 'go' branch in the master branch, with your suggestions. You can probably try it with

```sh
docker pull qmcgaw/private-internet-access
```

now (when [Travis is done building though](https://travis-ci.org/qdm12/private-internet-access-docker)). I'll close the issue for now, feel free to re-open it if it doesn't work.
