### ISSUE TITLE
docker-compose vs log

### ISSUE THREAD

**Issue by Frepke** [qdm12/private-internet-access-docker#73]
Hello Quentin,

First of all a big thanks for your hard work and awesome renewed container.

In my compose file I've the next settings:
      - DOT=on
      - DOT_PROVIDERS=cloudflare
      - DOT_VERBOSITY=1
      - DOT_VERBOSITY_DETAILS=0
      - DOT_VALIDATION_LOGLEVEL=0
      **- BLOCK_MALICIOUS=on
      - BLOCK_SURVEILLANCE=on
      - BLOCK_ADS=on**

The logfile gives me the following information:
    DNS over TLS:
     - Activated: on
     **- Malicious hostnames DNS blocking: on
     - NSA related DNS blocking: off**
     - Unblocked hostnames: 

kr.,
Frepke

**Comment by qdm12** [comment]
This looks like the old log, I think you did not pull the latest image or didn't restart the container properly to use the latest image.

The new environment variables are only valid for the latest image.

**Comment by Frepke** [comment]
Oops, 
Thanks

**Comment by Frepke** [comment]
Now with the latest image I've these settings:
      - BLOCK_MALICIOUS=on
      - BLOCK_SURVEILLANCE=**on**
      - BLOCK_ADS=on
and the log says:
DNS over TLS settings:
 |--DNS over TLS provider: 
  |--cloudflare
 |--Block malicious: enabled
 |--Block surveillance: **disabed**
 |--Block ads: enabled

**Comment by qdm12** [comment]
Yep, yet another mistake. It was still stuck on picking up `BLOCK_NSA`. It should now pick up both, and `BLOCK_NSA` for retrocompatibility.
