### ISSUE TITLE
Container does not start - [ERROR] Undefined error, with status 1 - 

### ISSUE THREAD

**Issue by generious** [qdm12/private-internet-access-docker#75]
Trying to set up the VPN throws back **[ERROR] Undefined error, with status 1**

Configuration used 
docker run -d --init --name=pia --cap-add=NET_ADMIN --device=/dev/net/tun -e REGION="Ireland" -e USER=xxxxxxx-e PASSWORD=xxxxxx -e EXTRA_SUBNETS=192.168.1.0/24 qmcgaw/private-internet-access

also tried with REGION="UK London" and REGION="CA Montreal"
and removed -e EXTRA_SUBNETS=192.168.1.0/24

Enabled: modprobe tun 

# docker version
Client: Docker Engine - Community
 Version:           19.03.5

Server: Docker Engine - Community
  Version:          18.09.1

also tried doing it docker compose and getting the exact same error.
Created a regular openvpn connection on my centos 8 server to pia and that worked so I know the credentials are fine.

Looks like this is failing because it cannot resolve uk-london.privateinternetaccess.com.

Can anyone see anything obvious here?

```
 =========================================
 =========================================
 ============= PIA CONTAINER =============
 ========================================
 =========================================
 == by github.com/qdm12 - Quentin McGaw ==
OpenVPN version: 2.4.7
Unbound version: 1.9.1
Iptables version: v1.8.3
TinyProxy version: 1.10.0
ShadowSocks version: 3.3.4

OpenVPN parameters:
 * Region: Ireland
 * Encryption: strong
 * Protocol: udp
 * Running without root: yes

DNS over TLS:
 * Activated: on
 * Malicious hostnames DNS blocking: off
 * NSA related DNS blocking: off
 * Unblocked hostnames: 

Local network parameters:
 * Extra subnets: 192.168.1.0/24
 * Tinyproxy HTTP proxy: off
 * ShadowSocks SOCKS5 proxy: off

PIA parameters:
 * Remote port forwarding: off

[INFO] /auth.conf already exists
[INFO] Launching Unbound to connect to Cloudflare DNS 1.1.1.1 over TLS...DONE
[INFO] Changing DNS to localhost...DONE
[INFO] Reading OpenVPN configuration...
 * Port: 1197
 * Domain: ireland.privateinternetaccess.com
[INFO] Detecting IP addresses corresponding to ireland.privateinternetaccess.com...
nslookup: can't resolve 'ireland.privateinternetaccess.com': Try again

**[ERROR] Undefined error, with status 1**
```

**Comment by qdm12** [comment]
That's a DNS issue related to Unbound. Anyway, I released a newer Docker image completely rewritten, do you mind trying it?

```sh
docker pull qmcgaw/godevcontainer
```

And then restart the container for it to use the latest image.
