### ISSUE TITLE
Error on container start environment var

### ISSUE THREAD

**Issue by bcjacob** [qdm12/private-internet-access-docker#76]
getting the following error on start:

```
ERROR   environment variable "TINYPROXY_LOG" value is "Info" and can only be one of: info, warning, error, critical
```

**Comment by Frepke** [comment]
You have to use info instead of Info

**Comment by bcjacob** [comment]
yep.  noticed it right after I submitted the issue

**Comment by qdm12** [comment]
Actually that's a mistake, I fixed it now you should use `Info`. Not sure what happens if you put `info` instead of `Info` as it's directly passed to tinyproxy which might not understand it.

On a side note, you should use shadowsocks it's much better than tinyproxy 👍
