### ISSUE TITLE
torrent tracker hostnames wont resolve

### ISSUE THREAD

**Issue by ljmerza** [qdm12/private-internet-access-docker#88]
I've tried a few different config settings. no `DOT_PROVIDERS`, with `DOT_PROVIDERS`, with and without `CUONTRY` and `CITY`, when mullvad does connect, none of my trackers on bit torrent are able to resolve.

```
VPNSP=mullvad
COUNTRY=USA
DOT_PROVIDERS=google,cloudflare
```

**Comment by qdm12** [comment]
As a first step, assuming your container is called `pia`, can you try

```sh
docker exec -it pia nslookup <yourtrackerhostname>
```

And post back the error message? Thanks!

You can also raise the DNS verbosity using [the env variables](https://github.com/qdm12/private-internet-access-docker#environment-variables) (i.e. `DOT_VERBOSITY=2` and `DOT_VERBOSITY_DETAILS=1` ) but that will likely produce a huge log.

**Comment by qdm12** [comment]
Ok, I believe I found the issue.

I only configured ipv4 addresses for upstream DNS over TLS servers (cloudflare, google, etc.). I'm adding their ipv6 addresses right now. It would probably only work for ipv4 only trackers and fail for ipv6 trackers.

**Comment by qdm12** [comment]
I added the DNS over TLS server ipv6 addresses, so it might work now. I also added an environment variable `DOT_IPV6` defaulting to `on` in case you want to try with Unbound not resolving using IPV6 (if it still does not work). I will close the issue for now, but feel free to comment and re-open the issue if it doesn't work.
