### ISSUE TITLE
Environment variable for ipaddress

### ISSUE THREAD

**Issue by benjaminpottier** [qdm12/private-internet-access-docker#90]
Would it be possible to add a feature so that in stead of (or in addition to) supplying REGION I could supply a specific public ipaddress, so that I get the same one every time?

**Comment by qdm12** [comment]
Yes I will do in the coming days.

**Comment by qdm12** [comment]
I just implemented a new environment variable `OPENVPN_TARGET_IP` that you can set to an ipv4 address for PIA or Mullvad, and it should force it to only use that one. Let me know if it works, I haven't got the time to test it out. Thanks!
