### ISSUE TITLE
Loosing connection on connected containers

### ISSUE THREAD

**Issue by gurabli** [qdm12/private-internet-access-docker#92]
Hi,
I was not able to follow up recently, but it was really nice to see that lotnof development was going on. Nice job! 

Bringig this up again, maybe there is already a solution I just missed. 

So I have the latest image up and running, and another container is connected, both on same docker compose yml. It works perfectly, but each day I loose connection on the connected container, and I have to restart it manually. Not PIA, it runs fine.
Any way or workaround for this? 

EDIT: using PIA. 

Thanks

**Comment by qdm12** [comment]
Thanks!

Are you sure you don't have a restart on the pia container? It should not disconnect for no reason. 

Anyway, I'll likely setup a shadowsocks client container with instructions quite soon as a lot of issues relates to losing connection to the container.

> EDIT: Using PIA

I also need to add an issue template haha with Mullvad and soon Windscribe it's getting out of hands to specify your situation :smile: Anyway thanks for specifying.

**Comment by gurabli** [comment]
Well, the PIA container did have a restart today, but don't see why. It was set on Always restart policy, now I set it to Unless-Stopped. Will monitor and see what happens.
As I understand, the container itself should not restart, just the connection to PIA server inside th container if the connection is broken for some reason, correct? So it reconnects automatically inside the container. And if this happens, it should not brake the connection on the linked container?

Will be glad to see the shadowsocks client instructions and how to use it. It will be somethig like:
PIA Container <-> Shadowsocks Clien container <-> Linked Containers

**Comment by qdm12** [comment]
If you run openvpn without root (default), it will exit the container and connected containers will lose their connection, even with an automated Docker restart.

If you run it with `OPENVPN_ROOT=yes`, it might reconnect without exiting and containers might not lose their connection, although I'm not 100% certain.

And you're right about that communication through shadowsocks. I'll work on it the coming days. It would also allow for example to restart the container with different parameters without restarting all connected containers. Let's keep this issue opened for now.

**Comment by gurabli** [comment]
Just a quick info. I have 

OPENVPN_ROOT=yes

set in docker compose for ENV. Still, in the logs I see:
```
OpenVPN parameters:
 * Region: Sweden
 * Encryption: normal
 * Protocol: udp
 * Running without root: yes
```
Any ideas?

**Comment by qdm12** [comment]
I think you're running an old Docker image, potentially really old :smile:  This is the way:

```
docker pull qmcgaw/private-internet-access
```

:wink:

**Comment by gurabli** [comment]
> I think you're running an old Docker image, potentially really old 😄 This is the way:
> 
> ```
> docker pull qmcgaw/private-internet-access
> ```
> 
> 😉

And yes, you are correct. Not pulled the latest.
But really don't get why. My docker-compose is:

```
services:
  vpn:
    image: qmcgaw/private-internet-access:latest
    container_name: vpn
```
Running docker-compose up for first time should pull the latest image (if this is the first time install). And I installed on this server for first time a few days ago.

**Comment by gurabli** [comment]
It is somehow better with latest container, but still loosing connection.
Not to hurry, but wonder if any news about the shadowsocks container? Would so much like to test it.

**Comment by qdm12** [comment]
I will do it this weekend, I will probably make a super light (~5MB) Go shadowsocks client container (based on an existing one doing server and client) especially tailored for this container.

**Comment by qdm12** [comment]
Hi Gurabli, do you mind trying with the image with tag `:persist-remote-ip`? It may allow connected containers to stay connected even if openvpn restarts on a ping timeout.

I worked on the shadowsocks client container this weekend but have no clue how to tunnel the entire traffic of the container through it :laughing: I will dig more.

**Comment by gurabli** [comment]
An important update: it turned out that qBittorrent versions higher than 4.2.1 are loosing the connection for some reason over VPN. See the issue here: [Link](https://github.com/qbittorrent/qBittorrent/issues/12386)

Downgraded qbittorrent container to version 4.2.1 and it is working now fine. 
However, I also pulled the `:persist-remote-ip` version on both systems, as even when I was using qbit version that was working, I always lost connection within a day or two. On another system it is oscam that lost connection after 24-48 hours. So testing now, will report back once I notice a lost connection.

**Comment by qdm12** [comment]
So how is it going? All the containers should lose the connection when openvpn reconnects, it shouldn't be just a single connected container losing the connection.

**Comment by qdm12** [comment]
So was it an issue with qbitorrent in the end? Should we close the issue? Thanks!

**Comment by gurabli** [comment]
> So was it an issue with qbitorrent in the end? Should we close the issue? Thanks!

Yes, the issue was with qbittorrent. It was really hard to debug. Maybe they already fixed this, but I'm still on a version that workes perfectly fine, so didn't upgrade yet. 
So yes, we can close this issue. The only one that reamins is that docker-compose can't rebuild/recreate connected containers, but that is not related to this issue.

**Comment by qdm12** [comment]
Cool, thanks. See that [Reddit post I just made on restarting the vpn container without restarting the linked containers](https://www.reddit.com/r/docker/comments/gdvod4/restart_container_with_network_stack_shared_with) hopefully someone can save us all.
