### ISSUE TITLE
change cypher and auth in a variable

### ISSUE THREAD

**Issue by Phorze** [qdm12/private-internet-access-docker#94]
Or even better, a custom ovpn file.

Would that be possible? Running on arm64 i would like to lower CPU usage by using

aes-128-gcm
ncp-disable
auth sha265

**Comment by qdm12** [comment]
For which VPN provider? And yes I can add that in env variables, although the vpn server might still override them depending on their configuration.

**Comment by Phorze** [comment]
In my case for PIA :-)

**Comment by qdm12** [comment]
From the article you sent, it seems aes-gcm is available on all ports so that will be added. However, I'm not sure about the auth algorithm, can you pick whichever you want with pia? Thanks!

**Comment by Phorze** [comment]
Yes, you can use both sha1 and sha256 independently of cypher.  

However,  ncp-disable seems mandatory for aes-128-gcm if I understand correctly.

**Comment by Phorze** [comment]
Tested:

      - PIA_ENCRYPTION=custom
      - OPENVPN_CYPHER=aes-128-gcm
      - OPENVPN_AUTH=sha256

The following occurred:
`environment variable "PIA_ENCRYPTION" value is "custom" and can only be one of: normal, strong`
Then tested:

      - OPENVPN_CYPHER=aes-128-gcm
      - OPENVPN_AUTH=sha256

Log:
```
openvpn: Fri Mar 27 14:55:38 2020 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1570', remote='link-mtu 1542'
openvpn: Fri Mar 27 14:55:38 2020 WARNING: 'cipher' is used inconsistently, local='cipher AES-256-CBC', remote='cipher BF-CBC'
openvpn: Fri Mar 27 14:55:38 2020 WARNING: 'auth' is used inconsistently, local='auth SHA256', remote='auth SHA1'
openvpn: Fri Mar 27 14:55:38 2020 WARNING: 'keysize' is used inconsistently, local='keysize 256', remote='keysize 128'
```

**Comment by qdm12** [comment]
Oops I forgot to remove the `custom` from the readme.
Just keep it to normal or strong (as it changes the port used and CA certificate). And then you can override the default cipher or auth algorithm.

For the warning in the logs, that's on PIA's side because their server are configured to use those 'remote' settings by default. It should not cause an issue and should still use the local defined settings. See https://www.privateinternetaccess.com/helpdesk/kb/articles/why-do-i-get-cipher-auth-warnings-when-i-connect

I'll fix the readme and then close the issue

**Comment by Phorze** [comment]
using "strong" and above cypher and auth settings i get the following:


```
root@rpi4:~# docker exec -it pia cat /etc/openvpn/target.ovpn
client
dev tun
nobind
persist-key
persist-tun
tls-client
remote-cert-tls server
ping 300
reneg-sec 0
compress
auth-nocache
mute-replay-warnings
pull-filter ignore "auth-token"
auth-retry nointeract
remote-random
verb 1
auth-user-pass /etc/openvpn/auth.conf
proto udp
cipher aes-256-cbc
auth sha256
```

**Comment by qdm12** [comment]
It's CIPHER not CYPHER :smile:

**Comment by Phorze** [comment]
Working now, ncp-disabled is also added
